ConvertFrom-StringData @'
ClearCcmExecDone = Tasklist for CcmExec has now been cleared
ClearCcmExecErr = Error occured
ClearCcmExecErrService = Error occurred while trying to restart service
ClearDNSCacheDone = Cache was removed
ClearNetIdCacheFinished = Removed these files:
CloseCurrentOpenRemoteConnectionsSuccess = Remote service restarted
GetLastBootUpTimeNoData = No computer was found
GetLastBootUpTimeNoDateInfo = Could not be reached
GetLastBootUpTimePropDateInfoTitle = Last boot
GetLastBootUpTimePropNameTitle = Computername
GetLastBootUpTimePropSMTitle = Last date from SysMan
GetLastLoggedInErrNoUser = User not found in AD
GetLastLoggedInStrCompNotFound = Computer name not found in SysMan
GetLastLoggedInStrCompTitle = Computername
GetLastLoggedInStrUserTitle = User
OpenWebPageStrDone = Website opened
RepairCmAgentStrDone = The CM Agent has now been restored
RepairO365LicensStrCimError = An error occurred with the connection
RepairO365LicensStrDone = The Office license repair script has now finished
RepairO365LicensStrError = Error occurred
ResetHostsFileFinished = Host file cleared
ResetOutlookNavigationPanelFinished = UI restored
ResetOutlookViewsFinished = Views restored
RestartSMSCMAgentStrDone = The CM Agent has now been restarted
SendToastSuccess = Message sent
StartCMAllMeasuresDone = All schedules have now been initialized in the CM Agent
StartCMAllMeasuresErrScheduling = Errors occurred with the following schemas
StartCMAppRefreshDone = All application control schedules have now been initialized in the CM Agent
StartCMAppRefreshErrScheduling = Errors occurred with the following schemas
StartCMNewApplicationsDone = Search for new application launches has started
StartCMNewApplicationsErr = Error occurred
StrAppId = Message from Service Desk
StrSameCostCenterPropName = CcPropName
SysManServerUrl = http://sysman.test.com/
'@
