ConvertFrom-StringData @'
ContentBtnSet = Save autoreply
ContentCbActivate = Activate autoreply
ContentCbCreateOOFEvent = Create event in the calendar?
ContentCbDeclineAllEventsForScheduledOOF = Also decline existing events during the period
ContentCbDeclineAllEventsForScheduledOOFTT = This will remove the events from the calendar. If the user is the organizer, the event will also be deleted for invited users.
ContentCbDeclineEventsForScheduledOOF = Decline existing meetings during the period?
ContentCbDeclineRequests = Decline meeting invitations
ContentCbScheduled = Set an end date
ContentCbSendExternal = Send to recipients outside the organization?
ContentGbEnd = End date for auto reply
ContentGbExternalAutoReply = Message outside the organization
ContentGbInternalAutoReply = Message within the organization
ContentGbStart = Auto reply start date
ContentRbExternalReplyAll = All
ContentRbExternalReplyContacts = Contacts only
ContentTblDeclineMeetingMessageTitle = Notification when meeting invitation is declined
ContentTblFoundUserTitle = Found account:
ContentTblIdTitle = Enter ID or email address
ContentTblOOFEventSubjectTitle = Event header
ContentTbSummaryTitle = Summary, these settings will be set when you press \"Save auto reply\"
LogSummary = Set the following settings for auto reply
StrAllRequestsIsDeclined = Existing events will be deleted
StrDisableAutoReply = Disables auto reply
StrDontSendExternal = Does not send externally
StrNoO365User = No user account in Office365 found
StrNoUser = No user found
StrOOFEventIsCreated = An event will be created in the calendar
StrRequestsIsDeclined = Invitations during the period will be refused
StrScheduledAutoReplyNotSet = Start and end dates must be set to use this setting
StrSendExternalAll = all
StrSendExternalOnlyContacts = only contacts on the account
StrSendExternalStart = Sending externally to
StrSetAutoReplyNotScheduled = Auto reply is active without end date
StrSetAutoReplyScheduled = Auto reply is scheduled from
StrSetAutoReplyScheduledManualEnd = until manually disabled (end date set to 5 years ahead)
StrSetAutoReplyScheduleEnd = until
StrSetAutoReplyStart = Sets auto reply to be sent
StrSetting = Working
StrSettingDone = Auto reply set
StrSettingInactiveDone = Auto reply disabled
'@
