ConvertFrom-StringData @'
CodeSysManUrl = https://sysman.test.com/sysman
ContentBtnCopyFrom = Copy groups
ContentBtnPerform = Run
ContentBtnRefetchGroups = Reload groups
ContentBtnUndo = Abort
ContentTblAddedUsersTitle = Added permissions
ContentTblApp = Select application
ContentTblAppGroupList = Select app group by double clicking
ContentTblComputerTitle = Computer that needs AD group
ContentTblCopyFromTitle = Copy groups from  ...
ContentTblGroupsChosen = Selected app groups
ContentTblLog = Changes made
ContentTblUsersAddPermission = Create permission
ContentTblUsersRemovePermission = Remove permission
ContentWindowTitle = Remove/Add app permissions
ErrCopyFromNotIdentified = Found no user with this ID
ErrMessageGetAppGroups = Retrieving app groups
ErrMessageGetUser = Get users
ErrMessageSetPassword = Set password
ErrMessageSetSettings = Set settings
ErrScriptPermissions = You lack the necessary permissions to run this script
ErrSysManGenError = Error connecting to SysMan
ErrSysManNoComputer = Computer not found in SysMan
ErrSysManNoSystem = System not found in SysMan
ErrUserNotFound = NotFound
LogInputAdd = For additions:
LogInputRemove = For removal:
LogMessageAdd = Added permissions:
LogMessageAddComputer = Computer received AD group:
LogMessageRemove = Permission removed:
MsgAddComputer = Computers that have received an AD group:
MsgMessageIntro = Have made below changes to the following
MsgNew = New permission
MsgNewPassword = new password
MsgNoAccount = Found no account for these
MsgRemove = Remove permission
QCont1 = Do you want to
QCont2 = perform
QCont3 = changes
QContErr = Some users do not have AD accounts
QContTitle = Continue
StrBORoleGrp = Rol_Servicedesk_Backoffice
StrSDRoleGrp = Rol_Servicedesk
StrDuplicates = There are duplicate values in the lists. Correct these and run again
StrDuplicatesTitle = Duplicates
StrErrorUsersTitle = ID not in AD
StrFinishMessage = changes made. A solution message has been copied to the clipboard
StrFinishMessageTitle = Done
StrGetADGroups = Fetching app groups...
StrGettingComputers = Fetching computers
StrGettingUser = Fetching users
StrGroupsCopied = groups was copied
StrGroupsTitle = Groups
StrLogMessage = Application
StrLogOut = For the permissions to take effect, the account needs to be logged out and then logged in again.
StrNoGroupsCopied = is not a member of any AD-grou for application
StrOpGrp = Rol_Katalog_Drift
StrOpLogPath = \\\\domain.test.com\\FolderTool
StrPreparing = Preparing...
StrProgressTitle = Applies group permissions
StrRemovedUsersTitle = Permission removed
StrSigGen = Sincerely
StrSigSD = Servicedesk
StrSigSD2 = Org2
StrSpecAddIntroApp3 = Thank you for your order.
StrSpecAddOutroApp3 = Login is required to access the page
StrSpecOrg = org6
StrSpecRemIntroApp3 = Permission has now been removed for
StrUserCopyFound = Found
'@
