ConvertFrom-StringData @'
CodeLockoutAddress = \\\\test.domain.com\\LockedoutLogs\$
CodeMsExchIgnoreOrg = OU=Org1
CodeOrgGrpCaptureRegex = CN=Org1_Wrk_(?<org>.{3})_PR_(?<role>.*_PC).*
CodeOrgGrpNamePrefix = CN=Org1_Wrk
CodeRegExAclIdentity = ^Domain.*_(C|R)$
ContentBtnCopyOutputData = Data
ContentBtnCopyOutputObject = Dataobject
ContentBtnCopyValue = Copy
ContentBtnDirView = Show
ContentBtnEnterFunctionInput = Run script
ContentBtnFetch = Fetch
ContentBtnFileView = Show
ContentBtnGetExtraInfo = Fetch extra info
ContentBtnRunVirusScan = Run virus check
ContentBtnSearch = Search
ContentChBGetComputerWarranty = Warranty period
ContentChBGetFromComputerProcesses = Processer
ContentChBGetFromPrintQueuePrintJobs = Printer queue
ContentChBGetFromSysMan = SysMan
ContentChBGetFromUserLockOut = Lockout list
ContentDgSearchResultsColNameTitle = Name (
ContentDgSearchResultsColObjClass = Objecttype
ContentLblUserADActiveCheck = AD Active
ContentLblUserADCheck = Available in AD
ContentLblUserADLockCheck = AD Unlocked
ContentLblUserADMailCheck = Email attribute set
ContentLblUserADmsECheck = msExchMailboxGuid
ContentLblUserOAccountCheck = O365-account created
ContentLblUserOExchCheck = Synced to Exchange
ContentLblUserOLicCheck = Has E3 license
ContentLblUserOLoginCheck = O365 login active
ContentMiObjDetailedHide = Simplified view
ContentNoMembersOfList = < No values >
ContentSavePropValueButton = Save
ContentTblCopyOutput = Copy:
ContentTblFailedSearchText = No items matched your search
ContentTblGetFromTitle = Get information from:
ContentTblMiAboutText = Ifs and buts
ContentTblMiCloseObj = Close object view
ContentTblMiComputerFunctionsText = Computer
ContentTblMiConnectO365ServicesText = Connect O365 Services
ContentTblMiCopyObj = Copy everything
ContentTblMiCopyObjSelected = Copy selected
ContentTblMiGroupFunctionsText = Group
ContentTblMiHideObj = Hide AD objects
ContentTblMiHideOutputView = Hide the output view
ContentTblMiO365Text = Office 365
ContentTblMiObjDetailed = Detailed view
ContentTblMiOtherFunctions = Other functions
ContentTblMiOutputHistoryText = Output history
ContentTblMiPrintQueueFunctionsText = Printer
ContentTblMiShowObj = View AD objects
ContentTblMiShowOutputView = Show the output view
ContentTblMiToolsText = Tools
ContentTblMiUserFunctionsText = User
ContentTblObjMenuTitle = Object activities
ContentTblOutputErrorsTitle = Error in execution
ContentTblOutputMenuTitle = The output view
ContentTblOutputTitle = Data from
ContentTblPropHandlerTitle = Handler
ContentTblPropHandlerTitleEmpty = No handler specified, button will not be displayed
ContentTblPropNameTT = Data source
ContentTblSearchHint = You can search by ID, group name, printer queue, IP address, or specify the path to a folder or file
ContentTblVisiblePropsTitle = Tick the values to be displayed in general view
ContentTBtnObjectDetailed = Select attributes to display in the default view
ContentTTMiCloseObj = Close the view and forget the object
ContentTTMiCopyObj = Copy all data from the object
ContentTTMiCopyObjSelected = Copy selected data from the object
ContentTTMiObjDetailedHide = Show simplified list
ContentTTMiObjDetailedShow = View detailed list
ContentTTTblContentTblMiShowHideObj = Show/hide the view for AD objects
ContentTTTblContentTblMiShowHideOutputView = Show/hide the output view
ErrForbiddenCmdLet = Banned CmdLet
ErrToolGuiNotPage = Gui is not defined with a Page object. The tool will therefore not be loaded
HDescCheckComputerOnline = Checks if the computer is online and reachable via scripts/tools
HDescClearPrintQueueJobs = Clear the printer queue
HDescGetSharedAccount = Fetching shared account connected to the computer
HDescMemberOf = Change the names to easy-to-read names
HDescOpenHomeDirectory = Open the folder in Windows Explorer
HDescOpenPrinterWebpage = Connect to the printer, via its IP, in Chrome
HTCheckComputerOnline = Check
HTClearPrintQueueJobs = Clear the printer queue
HTGetSharedAccount = Fetch shared account
HTMemberOf = Display easy to read
HTOpenHomeDirectory = Open in Explorer
HTOpenPrinterWebpage = Open the printer in Chrome
LogStrSearchItemTitle = AD-object
StrAccountNeverExpires = < No end date >
StrClearPrintJobs = Clears print queue
StrCompOperatingSystemVersion = version
StrComputerOnline = Online:
StrConnectO365Title = Connect to the O365 services
StrCopyOutputEnteredInput = This was entered as input
StrCopyOutputForAdObject = for AD objects
StrCopyOutputMessageP1 = The following data has been retrieved
StrCopyOutputMessageP2 = from script/function
StrCopyOutputMessagePTime = The script was executed
StrCopyOutputSynopsis = Description of function
StrDefaultHandlerDescription = Run code for attributes
StrDefaultMainTitle = Fetchalon
StrDirFileCount = files
StrDirFolderCount = folder
StrDirItemsCount = object
StrGrpNameSharedCompName = SA_Client
StrIdPrefix = Prefix
StrIdPropName = IdName
StrLockoutComputer = Computer
StrLockoutDate = Date
StrLockoutDomain = Domain
StrNoLockoutsFound = No lockouts found in the last 7 days
StrNoLockoutsFoundTitle = No lockouts
StrNoOwner = < No owner listed >
StrNoPrintJobs = No print jobs queued
StrNoScriptOutput = < No output >
StrOpensSeparateWindow = Opens in separate window
StrOrgDnPropName = OrgDn
StrPropertyCopied = Data copied to clipboard
StrPropList = List of values
StrPsGetCmdlet = PowerShell Get CmdLet
StrRunHandler = Run attribute script
StrScriptRunningWithoutRunspace = Will run without a separate thread, the window can be locked
StrSelectPropsDesc = Select by ticking the value to be displayed in the default view
StrSplash2 = Rearranging the furniture
StrSplash3 = Hacking CIA
StrSplashAddControlHandlers = Creating controls
StrSplashCreatingHandlers = Loading functions
StrSplashCreatingWindow = Creates main window
StrSplashFinished = Finished, good bye!
StrSplashReadingSettings = Loading settings
StrSysManApi = http://sysman.domain.com/SysMan/api/
StrVerbVirusScan = Search for threats
'@
