ConvertFrom-StringData @'
CodeAzureGrpName = ^(MB-)|(DL-)|(RES-)*\\w* (Funk)|(Dist)|(Resurs)|(Rum)
CodeMsExchIgnoreOrg = OU=Org1
CodeOrgGrpCaptureRegex = CN=Org1_Wrk_(?<org>.{3})_PR_(?<role>.*_PC).*
CodeOrgGrpNamePrefix = CN=Org1_Wrk
CodeRegExAclIdentity = ^Domain.*_(C|R)$
ContentBtnCopyOutputData = Data
ContentBtnCopyOutputObject = Dataobject
ContentBtnCopyValue = Copy
ContentBtnEnterFunctionInput = Run script
ContentBtnSearch = Search
ContentDgSearchResultsColNameTitle = Name (
ContentDgSearchResultsColObjClass = Objecttype
ContentMiObjDetailedHide = Simplified view
ContentMiShowHideOutputViewHide = Hide output view
ContentMiShowHideOutputViewNoOutput = No output
ContentMiShowHideOutputViewShow = Show output view
ContentNoMembersOfList = < No values >
ContentSavePropValueButton = Save
ContentTblAsterixWarning = When the search term has an asterix at the beginning, the search takes longer. Try to be as specific as possible.
ContentTblCopyOutput = Copy:
ContentTblFailedSearchText = No items matched your search
ContentTblFileInfoText = File
ContentTblMiAboutText = Ifs and buts
ContentTblMiCloseObj = Close object view
ContentTblMiComputerFunctionsText = Computer
ContentTblMiConnectO365ServicesText = Connect O365 Services
ContentTblMiCopyObj = Copy everything
ContentTblMiCopyObjSelected = Copy selected
ContentTblMiDirectoryInfoFunctionsText = Directory
ContentTblMiGetSysManInfo = Hämta extra info
ContentTblMiGetSysManInfoTt = Hämta information från SysMan
ContentTblMiGroupFunctionsText = Group
ContentTblMiHideObj = Hide AD objects
ContentTblMiO365Distributionlist = Distributionslist (O365)
ContentTblMiO365Resource = Resource (O365)
ContentTblMiO365Room = Room (O365)
ContentTblMiO365SharedMailbox = Shared mailbox (O365)
ContentTblMiO365User = Användare (O365)
ContentTblMiObjDetailed = Detailed view
ContentTblMiOtherFunctions = Other functions
ContentTblMiOutputHistoryText = Output history
ContentTblMiPrintQueueFunctionsText = Printer
ContentTblMiSeparateToolsText = Separate tools/applications
ContentTblMiShowObj = View AD objects
ContentTblMiToolsText = Tools
ContentTblMiUserFunctionsText = User
ContentTblObjMenuTitle = Object activities
ContentTblOutputErrorsTitle = Error in execution
ContentTblOutputMenuTitle = The output view
ContentTblOutputTitle = Data from
ContentTblPropHandlerTitle = Handlers exist for the attribute
ContentTblPropHandlerTitleEmpty = No handler specified, button will not be displayed
ContentTblPropNameTT = Data source
ContentTblSearchHint = You can search by ID, group name, printer queue, IP address, or specify the path to a folder or file. Asterix can be used as a 'wildcard'.
ContentTblSourceFilterTitle = Filtrera på datakälla
ContentTblVisiblePropsTitle = Tick the values to be displayed in general view
ContentTBtnObjectDetailed = Click here to select attributes to display in the default view
ContentTTMiCloseObj = Close the view and forget the object
ContentTTMiCopyObj = Copy all data from the object
ContentTTMiCopyObjSelected = Copy selected data from the object
ContentTTMiObjDetailedHide = Show simplified list
ContentTTMiObjDetailedShow = View detailed list
ContentTTTblContentTblMiShowHideObj = Show/hide the view for AD objects
ContentTTTblContentTblMiShowHideOutputView = Show/hide the output view
ErrForbiddenCmdLet = Banned CmdLet
ErrSearchO365NotConnected = No connection to Office 365 services, can't search Azure groups.
ErrToolGuiNotPage = Gui is not defined with a Page object. The tool will therefore not be loaded
LogStrPropHandlerRun = Ran handler for
LogStrSearchItemTitle = AD-object
LogToolStarted = Started
StrAccountNeverExpires = < No end date >
StrCompOperatingSystemVersion = version
StrComputerOnline = Online:
StrCopyOutputEnteredInput = This was entered as input
StrCopyOutputForAdObject = for AD objects
StrCopyOutputMessageDataTitle = Data output
StrCopyOutputMessageP1 = The following data has been retrieved
StrCopyOutputMessageP2 = from script/function
StrCopyOutputMessagePFinish = Script finished
StrCopyOutputMessagePStart = Script started
StrCopyOutputSynopsis = Description of function
StrDefaultHandlerDescription = Run code for attributes
StrDefaultMainTitle = Fetchalon
StrGrpNameSharedCompName = SA_Client
StrIdPrefix = Prefix
StrIdPropName = IdName
StrNoOwner = < No owner listed >
StrNoScriptOutput = < No output >
StrOpenMainWindowFound = Fetchalon is already started
StrOpensSeparateWindow = Opens in separate window
StrOrgDnPropName = OrgDn
StrOutputPropName = Property
StrOutputPropValue = Value
StrPHComputerOtherProcessListColId = ProcessID
StrPHComputerOtherProcessListColName = Name
StrPHComputerOtherProcessListError = Error occured when connecting to computer
StrPropDataNotFetched = < Data not fetched >
StrPropertyCopied = Data copied to clipboard
StrPropListTitle1 = List with
StrPropListTitle2 = values
StrPsGetCmdlet = PowerShell Get CmdLet
StrRunHandler = Run attribute script
StrScriptRunningWithoutRunspace = Will run without a separate thread, the window can be locked
StrSelectPropsDesc = Select by ticking the value to be displayed in the default view
StrSplash2 = Rearranging the furniture
StrSplashAddControlHandlers = Creating controls
StrSplashCheckO365Roles = Kontrollerar Office365 roller
StrSplashConnectedO365 = Redan inloggad till Office365 online tjänster:
StrSplashConnectO365 = Logga in till Office365 online tjänster
StrSplashCreatingHandlers = Loading functions
StrSplashCreatingWindow = Creates main window
StrSplashFinished = Finished, good bye!
StrSplashJoke1 = Hacking CIA
StrSplashJoke10 = Smile and wave
StrSplashJoke11 = Never have I ever...
StrSplashJoke2 = Chopping onions
StrSplashJoke3 = Drink more water
StrSplashJoke4 = Eat a fruit
StrSplashJoke5 = Don't panic
StrSplashJoke6 = Lorem ipsum
StrSplashJoke7 = Never a shoe without a ...
StrSplashJoke8 = Your shoelace is undone
StrSplashJoke9 = Remember the incident
StrSplashReadingSettings = Loading settings
StrSplashSkippingO365 = Skips the login to Microsoft 365 services
StrSubMenuGroupTitleSuffix = -functions
StrSysManApi = http://sysman.domain.com/SysMan/api/
StrSysAdmSANPrefix = sys
'@
