ConvertFrom-StringData @'
ContentBtnCheckForUpdates = Search for updates
ContentBtnClearErrorLogSearch = Abort search
ContentBtnClearLogSearch = Abort search
ContentBtnCopyErrorInfo = Copy info
ContentBtnCopyLogInfo = Copy
ContentBtnCopyRollbackInfo = Copy list
ContentBtnDiffCancel = Abort
ContentBtnDoRollback = Roleback fileversion
ContentBtnErrorLogSearch = Search
ContentBtnListRollbacks = List rollbacks
ContentBtnLogSearch = Search
ContentBtnOpenErrorLog = Open errorlog
ContentBtnOpenFailed = Open
ContentBtnOpenOutputFile = Open file
ContentBtnOpenPopupCopyLogInfo = Copy info
ContentBtnOpenRollbackFile = Open file
ContentBtnReadErrorLogs = Parse errorlogs
ContentBtnReadLogs = Parse logs
ContentBtnUpdatedInProdOpenBothFiles = Open both files
ContentBtnUpdatedInProdOpenDevFile = Open Dev-file
ContentBtnUpdatedInProdOpenDiffs = Open diff window
ContentBtnUpdatedInProdOpenProdFile = Open Prod-file
ContentBtnUpdateFailedScripts = Update checked files
ContentBtnUpdateScripts = Update selected files
ContentBtnUpdatesOpenBothFiles = Open both files
ContentBtnUpdatesOpenDevFile = Open Dev-file
ContentBtnUpdatesOpenDiff = Open diff window
ContentBtnUpdatesOpenProdFile = Open Prod-file
ContentCbCopyLogInfoIncludeErrorLogs = Include errorlogs
ContentCbCopyLogInfoIncludeOutputFiles = Include output-files
ContentCbLogsFilterSuccessFailed = Failed
ContentCbLogsFilterSuccessSuccess = Success
ContentCbRollbackFilterTypePs1 = ps1
ContentCbRollbackFilterTypePs1Tooltip = Script-file
ContentCbRollbackFilterTypePsd1 = psd1
ContentCbRollbackFilterTypePsd1Tooltip = Data/Localization-file
ContentCbRollbackFilterTypePsm1 = psm1
ContentCbRollbackFilterTypePsm1Tooltip = Module-file
ContentCbRollbackFilterTypeTxt = txt
ContentCbRollbackFilterTypeTxtTooltip = Documentation-/Information-file
ContentCbRollbackFilterTypeXaml = xaml
ContentCbRollbackFilterTypeXamlTooltip = GUI definitions file
ContentCbShowDevFiles = Show files in dev
ContentChbPublishFiles = Publish to prod
ContentDgDiffListColDevRow = Row in dev-file
ContentDgDiffListColLineNr = Rownumber
ContentDgDiffListColProdRow = Row in prod-file
ContentDgErrorLogsColLogDate = Log date
ContentDgFailedUpdatesColInvalidLocalizations = Invalid localizations
ContentDgFailedUpdatesColName = Updated file
ContentDgFailedUpdatesColObsoleteFunctions = Obsolete functions
ContentDgFailedUpdatesColOrphandLocalizations = Orphand localizations
ContentDgFailedUpdatesColScriptInfo = Script information
ContentDgFailedUpdatesColTODOs = Leftover TODO-notes
ContentDgFailedUpdatesColUpdateAnyway = Update anyway
ContentDgFailedUpdatesColWritesToLog = Writes to log
ContentDgInvalidLocalizationsColLineNumber = Rownumber
ContentDgInvalidLocalizationsColScriptLine = Linenumber
ContentDgInvalidLocalizationsColScriptVar = Variable
ContentDgLogsColLogDate = Log date
ContentDgLogsColOperator = Operator
ContentDgLogsColSuccess = Success
ContentDgObsoleteFunctionsColFunctionName = Function name
ContentDgObsoleteFunctionsColHelpMessage = Information
ContentDgObsoleteFunctionsColLineNumbers = Rownumber
ContentDgOrphandLocalizationsColValue = Variable value
ContentDgOrphandLocalizationsColVariable = Variable name
ContentDgRollbacksColFileName = Filename
ContentDgRollbacksColType = Filetype
ContentDgRollbacksColUpdated = Updated
ContentDgRollbacksColUpdatedBy = Updated by
ContentDgSIColHeaderInfoDesc = Description
ContentDgSIColHeaderTitle = Missing information
ContentDgTDColHeaderTextL = Linenumber
ContentDgTDColHeaderTextLN = Rownumber
ContentDgUpdatesColDevUpd = Updated in development
ContentDgUpdatesColName = Name
ContentDgUpdatesColNew = File is ...
ContentDgUpdatesColProdState = Development phase
ContentDgUpdatesColProdUpd = Updated in prod
ContentGbLogsDisplayPeriod = Filter on latest
ContentGbLogsFilter = Filter on success
ContentLblErrLogComputerName = Computername
ContentLblLogComputerNameTitle = Computername
ContentLblLogErrorLogTitle = Errorlog
ContentLblLogOutputFileTitle = File for output
ContentLblLogTextTitle = Logtext
ContentLblLogUserInputTitle = Entered input
ContentLblOperator = Operator
ContentLblRollbackFiltersTitle = File alternatives
ContentLblRollbackFilterTypeTitle = Filetype
ContentLblSeverity = Error severity
ContentLblUserInput = Entered input
ContentLlblErrorMessage = Error message
ContentRbLogsDisplayPeriodAll = All
ContentRbLogsDisplayPeriodRecent = Last week
ContentTblDevTitle = files in development
ContentTblInfo = Only update file you know you have changed yourself
ContentTblProdTitle = files in production
ContentTblPublishedNotInDev = These are updated in publication, but differ from local development
ContentTblTestTitle = files in test
ContentTblUpdatedInProd = These was updated in production, but not in dev.
ContentTiErrorLogs = Errorlogs
ContentTiFailedUpdates = Failed updates
ContentTiLogs = Logs
ContentTiRollback = Rollbackmachine
ContentTiUpdated = Updated
ContentTiUpdatedInProd = Updated in prod
ContentTiUpdates = Updates
LogFailedUpdates = script failed to update
LogFailedUpdatesName = Scriptname
LogFailedUpdatesTestResults = Testresult:
LogOpenDiffWindow = Checks diff
LogUpdatedIntro = Updated
StrCheckingUpdatesCheckFiles = Checks updates
StrCheckingUpdatesGetFiles = Get files
StrDiffRowAdded = < Row added >
StrDiffRowRemoved = < Row removed >
StrErrorlogsNotLoaded = Errorlogs has not been parsed yet
StrFailedTestCount = Number of failed tests
StrFunctionState = Associated function in
StrLogInfoCopyComputerName = Computername
StrLogInfoCopyDate = Date
StrLogInfoCopyError = Error
StrLogInfoCopyErrorFilePath = File path
StrLogInfoCopyLogText = Logtext
StrLogInfoCopyOperator = Operator
StrLogInfoCopyOutputFile = Output
StrLogInfoCopyOutputFilePath = File path
StrLogInfoCopySuccess = Success
StrLogInfoCopyTitle = Log-info for script
StrLogSearchNoType = No type selected
StrNewFileTitle = < New file >
StrNoFailedSelected = No files selected for update
StrNoScriptfile = No scriptfile containing script information was found
StrNotAllowedAnyway = Script could not be updated, since it violates mandatory rules
StrNoUpdaterSpecified = <Not specified>
StrNoUpdates = No files updated
StrRollbackDone = File rolled back
StrRollbackInfoCopyFileLogs = File versions
StrRollbackInfoCopyTitle = Update history for
StrRollbackInfoCopyUpdated = Date
StrRollbackInfoCopyUpdater = Updated by
StrRollbackName = updated
StrRollbackPathNotFound = File was not found in production. This file may have been renamed or moved, and should not be rolled back.
StrRollbackVerification = Do you want to replace the file in production with this file?
StrRollbackVerificationDate = File version to rolle back:
StrRollbackVerificationPath = File to replace:
StrScriptState = Associated script in
StrUpdatedFileIsNew = New
StrUpdatedFileIsUpdated = Updated
StrUpdates = updated files
StrUpdatesInProd = files was updated in production but not in dev
'@
