ConvertFrom-StringData @'
ContentBtnLoadCase = Read case information
ContentBtnRemoveCaseInfo = Delete case file
ContentBtnReset= Clear data
ContentBtnSaveCase = Save
ContentCbCategoryList = < Select >, System, Security, Client, Printer, Telephony, Wired network, Wireless network, Other
ContentCbOrderedArticleList = < Select >, Other article, User support, Workplace technician time (SLSO), General service request for an application at Region Stockholm for Service desk, Service catalog, Referral, Non-standard service catalog, Complaint, Account order, Account management, Cost article, ListOn - Listing extract, New password, Other
ContentCbSubCategoryClient = < Select >, Disk space, Login, Application missing, Application installation, Hardware, Peripherals, Performance
ContentCbSubCategoryPrinter = < Select >, Settings, Hardware error, Printer missing on computer
ContentCbSubCategorySystem = < Select >, Authorization, Login, The application does not start, The application is not available, Long response times, Function does not work
ContentCbSubCategorySecurity = < Select >, Virus, Phishing, Other security incident
ContentCbSubCategoryTelephony = < Select >, Calls, Hardware, Mobile Data, Fax
ContentCbSubCategoryWired_network = < Select >, Missing connection, Losing connection, Slow network, Broken network socket
ContentCbSubCategoryWireless_network = < Select >, Missing connection, Losing connection, Slow network, Poor coverage
ContentCbSubCategoryOther = < Select >, Other
ContentCbWayOfContactList = < Select >, Telephone, Personal contact
ContentGbOrdererInfo = Info Customer
ContentGbUserInfo = Info User
ContentLblCaseEndMessageTitle = Solution message
ContentLblCategoryTitle = Category
ContentLblComputerNameTitle = Computer name
ContentLblConfigObjTitle = Configuration object
ContentLblConfigObjTitleTT = cmdb_ci
ContentLblDescTitle = Case description
ContentLblInternalAddressTitle = Internal address
ContentLblIpAddressTitle = IP-address
ContentLblNetworkSocketTitle = Network socket
ContentLblOrderedArticleTitle = Item ordered
ContentLblOrdererIdTitle = Id
ContentLblOrdererMailInvalid = Email address not valid
ContentLblOrdererMailTitle = Email address
ContentLblOrdererTelephoneInvalid = Phone number not valid
ContentLblOrdererTelephoneTitle = Phone number
ContentLblPrinterQueueTitle = Printer queue
ContentLblServiceTitle = Service
ContentLblServiceTitleTT = business_service
ContentLblSubCategoryTitle = Subcategory
ContentLblTitleTitle = Title
ContentLblUserIdTitle = Id
ContentLblUserIdInvalid = Id not valid
ContentLblOrdererIdInvalid = Id not valid
ContentLblUserMailInvalid = Email address not valid
ContentLblUserMailTitle = Email address
ContentLblUserTelephoneInvalid = Phone number not valid
ContentLblUserTelephoneTitle = Phone number
ContentLblWayOfContactTitle = Way of contact
ContentLblWorklogTitle = Working log
ContentTBtnInc = INC
ContentTBtnRitm = RITM
StrJsonFileName = CM backup data
StrSaveTo = Data saved to
StrSelectCase = < Select case info file >
'@
