ConvertFrom-StringData @'
CodeRegKbSummaryReqAdGrps = (Rol_SD_Backoffice)|(Rol_SD_OpRes)
ContentBtnAddInputVariable = New variable
ContentBtnAddInputVariableBool = New variable
ContentBtnAddInputVariableList = New variable list
ContentBtnAddSettingTitle = Add setting
ContentBtnCheckForUpdates = Search for updates
ContentBtnClearErrorLogSearch = Abort search
ContentBtnClearLogSearch = Abort search
ContentBtnCopyErrorInfo = Copy info
ContentBtnCopyLogInfo = Copy
ContentBtnCopyRollbackInfo = Copy list
ContentBtnCreateCodeTemplate = Create code template
ContentBtnCreateKdSummary = Create summary for knowledge database
ContentBtnDiffCancel = Abort
ContentBtnDoRollback = Roleback fileversion
ContentBtnErrorLogSearch = Search
ContentBtnListRollbacks = List rollbacks
ContentBtnLogSearch = Search
ContentBtnOpenErrorLog = Open errorlog
ContentBtnOpenFailed = Open
ContentBtnOpenOutputFile = Open file
ContentBtnOpenPopupCopyLogInfo = Copy info
ContentBtnOpenRollbackFile = Open file
ContentBtnReadErrorLogs = Parse errorlogs
ContentBtnReadErrorLogsAgain = Parse errorlogs (again)
ContentBtnReadLogs = Parse logs
ContentBtnReadLogsAgain = Parse logs (again)
ContentBtnResetTemplateInfo = Reset
ContentBtnUpdatedInProdOpenBothFiles = Open both files
ContentBtnUpdatedInProdOpenDevFile = Open Dev-file
ContentBtnUpdatedInProdOpenDiffs = Open diff window
ContentBtnUpdatedInProdOpenProdFile = Open Prod-file
ContentBtnUpdateFailedScripts = Update checked files
ContentBtnUpdateScripts = Update selected files
ContentBtnUpdatesOpenBothFiles = Open both files
ContentBtnUpdatesOpenDevFile = Open Dev-file
ContentBtnUpdatesOpenDiff = Open diff window
ContentBtnUpdatesOpenProdFile = Open Prod-file
ContentCbCopyLogInfoIncludeErrorLogs = Include errorlogs
ContentCbCopyLogInfoIncludeOutputFiles = Include output-files
ContentCbLogsFilterSuccessFailed = Failed
ContentCbLogsFilterSuccessSuccess = Success
ContentCbRollbackFilterTypePs1 = ps1
ContentCbRollbackFilterTypePs1Tooltip = Script-file
ContentCbRollbackFilterTypePsd1 = psd1
ContentCbRollbackFilterTypePsd1Tooltip = Data/Localization-file
ContentCbRollbackFilterTypePsm1 = psm1
ContentCbRollbackFilterTypePsm1Tooltip = Module-file
ContentCbRollbackFilterTypeTxt = txt
ContentCbRollbackFilterTypeTxtTooltip = Documentation-/Information-file
ContentCbRollbackFilterTypeXaml = xaml
ContentCbRollbackFilterTypeXamlTooltip = GUI definitions file
ContentCbShowDevFiles = Show files in dev
ContentChbPublishFiles = Publish to prod
ContentDgDiffListColDevRow = Row in dev-file
ContentDgDiffListColLineNr = Rownumber
ContentDgDiffListColProdRow = Row in prod-file
ContentDgErrorLogsColLogDate = Log date
ContentDgFailedUpdatesColInvalidLocalizations = Invalid localizations
ContentDgFailedUpdatesColName = Updated file
ContentDgFailedUpdatesColObsoleteFunctions = Obsolete functions
ContentDgFailedUpdatesColOrphandLocalizations = Orphand localizations
ContentDgFailedUpdatesColScriptInfo = Script information
ContentDgFailedUpdatesColTODOs = Leftover TODO-notes
ContentDgFailedUpdatesColUpdateAnyway = Update anyway
ContentDgFailedUpdatesColWritesToLog = Writes to log
ContentDgInvalidLocalizationsColLineNumber = Rownumber
ContentDgInvalidLocalizationsColScriptLine = Linenumber
ContentDgInvalidLocalizationsColScriptVar = Variable
ContentDgLogsColLogDate = Log date
ContentDgLogsColOperator = Operator
ContentDgLogsColSuccess = Success
ContentDgObsoleteFunctionsColFunctionName = Function name
ContentDgObsoleteFunctionsColHelpMessage = Information
ContentDgObsoleteFunctionsColLineNumbers = Rownumber
ContentDgOrphandLocalizationsColValue = Variable value
ContentDgOrphandLocalizationsColVariable = Variable name
ContentDgRollbacksColFileName = Filename
ContentDgRollbacksColType = Filetype
ContentDgRollbacksColUpdated = Updated
ContentDgRollbacksColUpdatedBy = Updated by
ContentDgSIColHeaderInfoDesc = Description
ContentDgSIColHeaderTitle = Missing information
ContentDgTDColHeaderTextL = Linenumber
ContentDgTDColHeaderTextLN = Rownumber
ContentDgUpdatesColDevUpd = Updated in development
ContentDgUpdatesColName = Name
ContentDgUpdatesColNew = File is ...
ContentDgUpdatesColProdState = Development phase
ContentDgUpdatesColProdUpd = Updated in prod
ContentGbErrorLogsDisplayPeriod = Filter on latest
ContentGbLogsDisplayPeriod = Filter on latest
ContentGbLogsFilter = Filter on success
ContentLblErrLogComputerName = Computername
ContentLblLogComputerNameTitle = Computername
ContentLblLogErrorLogTitle = Errorlog
ContentLblLogOutputFileTitle = File for output
ContentLblLogTextTitle = Logtext
ContentLblLogUserInputTitle = Entered input
ContentLblOperator = Operator
ContentLblRollbackFiltersTitle = File alternatives
ContentLblRollbackFilterTypeTitle = Filetype
ContentLblSeverity = Error severity
ContentLblUserInput = Entered input
ContentLlblErrorMessage = Error message
ContentRbCodeTypeFunction = Function
ContentRbCodeTypeTool = Tool
ContentRbErrorLogsDisplayPeriodAll = All
ContentRbErrorLogsDisplayPeriodRecent = Last week
ContentRbFuncNoteTypeInfo = Information
ContentRbFuncNoteTypeWarning = Warning
ContentRbLogsDisplayPeriodAll = All
ContentRbLogsDisplayPeriodRecent = Last week
ContentTblAllowedUsersTitle = User with permission (enter admin id)
ContentTblAuthorTitle = Author (if other than yourself)
ContentTblCodeTypeTitle = Select type of codetemplate
ContentTblDescriptionTitle = Description
ContentTblDevTitle = files in development
ContentTblExistingSubMenus = Existing submenus
ContentTblExistingSubMenusTitle = Existing submenus for selected objecttype
ContentTblExpFuncHeader = Settings for function
ContentTblExpToolHeader = Settings for tool
ContentTblFuncNoRunspaceTitle = Do not use separate runspace
ContentTblFuncNote = Note
ContentTblFuncObjectClassTitle = Objectclass
ContentTblFuncOutputType = Type of outputdata
ContentTblFuncSearchedItemRequest = Searched item is wanted
ContentTblInfo = Only update file you know you have changed yourself
ContentTblInputDataBoolTitle = Inputdata as true or false
ContentTblInputDataListTitle = Inputdata with optionslist
ContentTblInputDataTitle = Inputdata
ContentTblInvalidateDateTimeTitle = Last time as active
ContentTblMenuItemTitle = Menuitem
ContentTblNameTitle = Name
ContentTblProdTitle = files in production
ContentTblRequiredAdGroupsTitle = AD-groups with permission
ContentTblStateTitle = Development state
ContentTblSubMenuNewInfo = Select an existing submenu, or enter the name of a new one
ContentTblSubMenuTitle = Submenu name
ContentTblSynopsisTitle = Synopsis
ContentTblTestTitle = files in test
ContentTblToolObjectOperationsTitle = Objectoperation
ContentTblToolSeparateTitle = Separate
ContentTblUpdatedInProd = These was updated in production, but not in dev.
ContentTblValidStartDateTimeTitle = Becomes active
ContentTiErrorLogs = Errorlogs
ContentTiFailedUpdates = Failed updates
ContentTiKbSummary = KB-summary
ContentTiLogs = Logs
ContentTiNewTemplate = New function/tool
ContentTiRollback = Rollbackmachine
ContentTiUpdated = Updated
ContentTiUpdatedInProd = Updated in prod
ContentTiUpdates = Updates
ContentTtGridAllowedUsersInfo = A list of users who should be given special access to use the feature/tool. These will be authorized even if a special AD group is specified for authorization. The list may be applicable if the code is in the test phase and selected people need to check the functionality.
ContentTtGridAuthorInfo = Who should be listed as the responsible author/developer. This is indicated if someone other than yourself is responsible. The person responsible will then also receive an email about the error report or comment through the "Send error report" tool. Enter the id in the box.
ContentTtGridDescriptionInfo = A reasonably detailed description of what the function/tool ​​does, in case it needs to be informed how it works, and, for example, what the result will look like.
ContentTtGridInputDataBoolInfo = Variables to be set as true or false before starting the function. The variable can also be specified as mandatory, and must then be specified before the function can be started. The value of each given variable will be copied to the function as a boolean.
ContentTtGridInputDataInfo = Variables to be specified before starting the function. The variable can also be specified as mandatory, and must then be specified before the function can be started. The value of each given variable will be copied to the function as a string.
ContentTtGridInputDataListInfo = Variables to be specified based on a specified list before starting the function. The variable can also be specified as mandatory, and must then be specified before the function can be started. The value of each given variable will be copied to the function as a string.
ContentTtGridInvalidateDateTimeInfo = This indicates the date and time when the feature/tool ​​can no longer be used.
ContentTtGridMenuItemInfo = Which text should be displayed in the menu bar. This text must not contain 'underscore' ('_') and must be clear with the purpose of the function/tool.
ContentTtGridNameInfo = Name of the function/tool. For tools, this will be the base name of the file/s. The name cannot be put in the info block at the beginning of the code. The name must have an approved verb as a prefix.
ContentTtGridNoRunspaceInfo = If the function is specified with NoRunspace, the code will run in the same process as the main window. This can be good in some situations when a separate process cannot use the required permissions or process info. The fact that the function uses the same process means that the window will be locked until the function has finished running.
ContentTtGridNoteInfo = Enter information that may be helpful to display before starting the function. The text can be entered as information or warning.
ContentTtGridObjectClassInfo = Choose which object type the function should work against/on. The menu bar will be placed in the corresponding menu specific to the object type. This also means that the function will get access to the searched object if the type is the same. If this is not selected, the function will be placed in the "OtherFunctions" module and the menu bar will then be placed in the "Other Functions" menu.
ContentTtGridObjectOperationsInfo = Select the object type that the tool works with. The menu bar will be placed in the corresponding menu specific to the object type. This also means that the tool will have the searched object copied to it when the tool starts. If this is not selected, the menu bar will be placed in the "Tools" menu.
ContentTtGridOutputTypeInfo = Define how the data output from the function is shaped or how it should be displayed. 'String' - Data will be formatted as a string and will be displayed as text without special formatting. 'ObjectList' - Data will be a list of objects. The objects will be listed with all attributes in a table. 'List' - Data will be a list of strings. 'None' - Data will not be returned by the function.
ContentTtGridRequiredAdGroupsInfo = One or more AD groups users must be a member of for the function/tool ​​to be available. This does not take precedence over AllowedUsers. If this is left blank, everyone will have permission.
ContentTtGridSearchedItemRequestInfo = Enter the function's need for searched objects. 'None' - No need and searched object will not be copied to the function. 'Allowed' - Searched item can be used, but is not required. If an object has been searched and loaded, it will be copied to the function on startup. 'Required' - Searched item is required and the menu bar will not be visible if no item has been loaded.
ContentTtGridSeparateInfo = Specify whether the tool should be created as a separate tool. This means that the GUI must be handled by the tool itself and will therefore be opened as a separate window. When the tool is started, a separate process will be created, in which the tool works. This also means that no information will be available in the main window. When the main window is closed, an attempt is made to close the tool's window as well.
ContentTtGridStateInfo = What development phase is the code in? Dev means that it is under development and will only be able to be run in the development environment. Test and Prod will be available for publication.
ContentTtGridSubMenuInfo = Specifies whether the menu bar should be placed in a submenu.
ContentTtGridSynopsisInfo = Synopsis, or short description. This should be no longer than one sentence and should generally describe the purpose of the function/tool.
ContentTtGridValidStartDateTimeInfo = This indicates the date and time when the function/tool ​​can start to be used.
ContentTtRbFuncNoteTypeInfo = The information will be displayed when the function is started from the menu. If the function has no input, but has information, the operation will be paused before the function is executed.
ContentTtRbFuncNoteTypeWarning = The note should be a warning. The warning will be displayed when the function is started from the menu. If the function has no input, but has a warning, the operation will be paused before the function is executed. The warning must be acknowledged before the function can be started.
CvsFuncObjectClassList = Directory,DirectoryInfo;File,FileInfo;User,User;Group,Group;Computer,Computer;Printer,Print queue;Other,Other;
CvsToolObjectOperationsList = Directory,DirectoryInfo;File,FileInfo;User,User;Group,Group;Computer,Computer;Printer,Print queue;Other,Other;
ErrNewCodeTemplateAllowedUsersNotFound = One or more IDs were not found
ErrNewCodeTemplateAuthorNotFound = No user found with the given name
ErrNewCodeTemplateNoIdentifyableId = Not an identifiable ID
ErrNewCodeTemplateBadInvalidateDate = Valid end date string
ErrNewCodeTemplateBadValidDate = Valid date string for start
ErrNewCodeTemplateDefaultValNotInOptionsList = This value is not in the list
ErrNewCodeTemplateDescriptionEmpty = Description must be provided
ErrNewCodeTemplateDescriptionNotGiven = Description must be provided
ErrNewCodeTemplateEndBeforeNow = End date has already been
ErrNewCodeTemplateEndBeforeStart = End date cannot be before start date
ErrNewCodeTemplateEndParseError = Unable to convert text to valid date/time. Correct format is 'YYYY-MM-DD hh:mm:ss'
ErrNewCodeTemplateInputNameExists = The name has already been specified for another input variable
ErrNewCodeTemplateInputNameInvalidCharacter = The name may only contain letters
ErrNewCodeTemplateMenuItemEmpty = Menu item must be specified
ErrNewCodeTemplateMenuItemExists = Given text is used for another function/tool, which can be confusing.
ErrNewCodeTemplateMenuItemInvalidCharacters = The text contains illegal characters. The text should only be letters, without underscores
ErrNewCodeTemplateMenuItemUnderscore = The text contains '_' which can be set with keyboard shortcuts
ErrNewCodeTemplateMissingCodeType = No code template selected
ErrNewCodeTemplateMissingDescription = Description
ErrNewCodeTemplateMissingFuncObjectClass = Object class function should work
ErrNewCodeTemplateMissingFuncOutputType = Type of output
ErrNewCodeTemplateMissingFuncSearchedItemRequest = Need for searched object
ErrNewCodeTemplateMissingInfo = Unable to continue as the following required information is missing
ErrNewCodeTemplateMissingInputDataBoolVarNoDesc = One or more inputs that are true or false have no description
ErrNewCodeTemplateMissingInputDataListVarNoDesc = One or more input data with selection list has no description
ErrNewCodeTemplateMissingInputDataListVarNoList = One or more inputs with selection list have no selection list
ErrNewCodeTemplateMissingInputDataVarNoDesc = One or more inputs have no description
ErrNewCodeTemplateMissingMenuItem = Menu item
ErrNewCodeTemplateMissingName = Name
ErrNewCodeTemplateMissingNameVerb = Verb prefix
ErrNewCodeTemplateMissingState = Development state
ErrNewCodeTemplateMissingSynopsis = Synopsis
ErrNewCodeTemplateRequiredAdGroupsNotFound = One or more names were not found
ErrNewCodeTemplateStartAfterEnd = Start date cannot be after end date
ErrNewCodeTemplateStartEndSame = The start and end dates cannot be the same
ErrNewCodeTemplateStartParseError = Unable to convert text to valid date/time. Correct format is 'YYYY-MM-DD hh:mm:ss'
ErrNewCodeTemplateStateMissing = Development state must be specified
ErrNewCodeTemplateSubMenuInvalidCharacters = The text for the submenu may only contain letters
ErrNewCodeTemplateSynopsisEmpty = Synopsis must be provided
ErrNewcodeTemplateSynopsisUnderscore = The text contains '_' which can be set with keyboard shortcuts
ErrNewCommandIllegalCharacters = The name contains illegal characters
ErrNewCommandNameExists = The specified name already exists
ErrNewCommandNoNameInput = A name must be entered
LogFailedUpdates = script failed to update
LogFailedUpdatesName = Scriptname
LogFailedUpdatesTestResults = Testresult:
LogOpenDiffWindow = Checks diff
LogUpdatedIntro = Updated
StrAdmPrefix = sys
StrCheckingUpdatesCheckFiles = Checks updates
StrCheckingUpdatesGetFiles = Get files
StrDiffRowAdded = < Row added >
StrDiffRowRemoved = < Row removed >
StrErrorlogsNotLoaded = Errorlogs has not been parsed yet
StrFailedTestCount = Number of failed tests
StrFunctionCreated = Function has now been created and placed in the module file. Do you want to open the file?
StrFunctionState = Associated function in
StrIcInputDataBoolDescriptionTitle = Description
StrIcInputDataBoolMandatoryTitle = Mandatory
StrIcInputDataBoolNameTitle = Variablename
StrIcInputDataDescriptionTitle = Description
StrIcInputDataListDefaultValueTitle = Default value
StrIcInputDataListDescriptionTitle = Description
StrIcInputDataListMandatoryTitle = Mandatory
StrIcInputDataListNameTitle = Variablename
StrIcInputDataListOptionslistTitle = Options list
StrIcInputDataMandatoryTitle = Mandatory
StrIcInputDataNameTitle = Variablename
StrKbSummaryAcceptsSI = (Accepts searched item)
StrKbSummaryAvailableForBoTitle = Available for BO
StrKdSummaryCommands = Functions / Tools
StrKbSummaryCopied = Summary copied to clipboard
StrKdSummaryDescription = Description of function/tool
StrKdSummaryMenuItem = Menu item
StrKbSummaryNeedsSI = (Requires searched item)
StrKbSummaryPreamble = <h3>List explanation</h3><p>The list shows the name (this is the text that appears in the menus), as well as an description of what the function/tool does.</p><p>&nbsp;</p><h3>Explanation different text styles</h3><p><em>Italics - This is a tool where all the GUI is displayed in the main window</em></p><p><strong>Bold - This is a tool that opens in its own, separate window</strong></p><p><span style="text-decoration: underline;">Underlined - This opens a link in Chrome, or opens/starts another application, most give no output</span></p><p>&nbsp;</p><h3>Input for functions</h3><p>How input should be specified for functions should be informed when the function is initialized, either as one value, or as several. This is explained above the textbox for the input value.</p><p>If the value is mandatory for the function, a red star will be displayed. There is no check of the value, such as spelling or that e.g. a computer has that name, before the function runs. This is taken care of by the function.</p><p>&nbsp;</p><h4>Requires searched item</h4><ul style="list-style-position: inside;"><li>The function is marked in green in front of the text in the menu</li><li><strong>Requires</strong> that searched ites have been searched and loaded, otherwise the menuitem will not be displayed</li><li>The function only requires the object as input and will start immediately</li></ul><h4>Accepts searched item</h4><ul style="list-style-position: inside;"><li>The function is marked in yellow in front of the text in the menu</li><li>The function can work with searched object and takes its name as input</li><li>Searched object's name will be entered in the first text box</li></ul><p>&nbsp;</p>
StrKbSummarySubCategoryTitlePrefix = Submenu
StrLogInfoCopyComputerName = Computername
StrLogInfoCopyDate = Date
StrLogInfoCopyError = Error
StrLogInfoCopyErrorFilePath = File path
StrLogInfoCopyLogText = Logtext
StrLogInfoCopyOperator = Operator
StrLogInfoCopyOutputFile = Output
StrLogInfoCopyOutputFilePath = File path
StrLogInfoCopySuccess = Success
StrLogInfoCopyTitle = Log-info for script
StrLogSearchNoType = No type selected
StrNewFileTitle = < New file >
StrNoFailedSelected = No files selected for update
StrNoScriptfile = No scriptfile containing script information was found
StrNotAllowedAnyway = Script could not be updated, since it violates mandatory rules
StrNoUpdaterSpecified = <Not specified>
StrNoUpdates = No files updated
StrRollbackDone = File rolled back
StrRollbackInfoCopyFileLogs = File versions
StrRollbackInfoCopyTitle = Update history for
StrRollbackInfoCopyUpdated = Date
StrRollbackInfoCopyUpdater = Updated by
StrRollbackName = updated
StrRollbackPathNotFound = File was not found in production. This file may have been renamed or moved, and should not be rolled back.
StrRollbackVerification = Do you want to replace the file in production with this file?
StrRollbackVerificationDate = File version to rolle back:
StrRollbackVerificationPath = File to replace:
StrScriptState = Associated script in
StrSeparateToolCreated = Script file has now been created. Do you want to open the file?
StrUpdatedFileIsNew = New
StrUpdatedFileIsUpdated = Updated
StrUpdates = updated files
StrUpdatesInProd = files was updated in production but not in dev
'@
