ConvertFrom-StringData @'
ContentBtnExport = Export
ContentBtnGetInfo = Get trace info
ContentBtnReset = Reset
ContentBtnSearch = Search
ContentDgColReceived = Received
ContentDgColReceiver = Receiver
ContentDgColSender = Sender
ContentDgColStatus = Status
ContentDgColSubject = Subject
ContentExpExtraSettings = Other search settings
ContentTblEndTitle = End date
ContentTblFromIpTitle = From IP
ContentTblFromIpTitleTt = For incoming messages, the value of FromIP is the public IP address of the SMTP email server that sent the message
ContentTblInfoActionTitle = Action
ContentTblInfoDataTitle = Data
ContentTblInfoDateTitle = Date
ContentTblInfoDetailTitle = Detail
ContentTblInfoEndDateTitle = End date
ContentTblInfoEventTitle = Event
ContentTblInfoIndexTitle = Index
ContentTblInfoOrganizationTitle = Organization
ContentTblInfoRecipientAddressTitle = Recipient address
ContentTblInfoSenderAddressTitle = Sender address
ContentTblInfoStartDateTitle = Start date
ContentTblMessageIdTitle = Message ID
ContentTblMessageTraceIdTitle = Messagetrace ID
ContentTblPageSizeTitle = Page Size
ContentTblReceiver = Receiver
ContentTblSender = Sender
ContentTblStart = Start date
ContentTblStatusTitle = Receive status
ContentTblToIpTitle = To IP
ContentTblToIpTitleTt = The ToIP parameter filters the results by the destination IP address. For outgoing messages, the value of ToIP is the public IP address in the resolved MX record for the destination domain. For incoming messages to Exchange Online, the value is blank.
ContentTiInfo = Message trace details
ContentTiTrace = Message trace
ErrNoMessageTraceDetails = No info was found, try again
LogExported = Export data
LogSearchDates = Search dates
LogTraceCount = mail was found
StrDone = Messagetrace received
StrExportDateFormat = YYYY-MM-DD tt:mm:ss
StrExportDefaultFileName = Messagetrace export
StrExportFileNameDates = Searchdate
StrExportFileNameFo = To
StrExportFileNameFrom = From
StrExportSaved = Excel-file was saved
StrInvalidEmail = Invalid e-mail address
StrOutputFileNamePrefix = O365 Messagetrace
StrStatusDelivered = The message was delivered to its destination.
StrStatusExpanded = There was no message delivery because the message was addressed to a distribution group and the membership of the distribution was expanded.
StrStatusFailed = Message delivery was attempted and it failed or the message was filtered as spam or malware, or by transport rules.
StrStatusFilteredAsSpam = The message was marked as spam.
StrStatusGettingStatus = The message is waiting for status update.
StrStatusNone = The message has no delivery status because it was rejected or redirected to a different recipient.
StrStatusPending = Message delivery is underway or was deferred and is being retried.
StrStatusQuarantined = The message was quarantined.
'@
