ConvertFrom-StringData @'
CodeGrpDescriptionMatch = \\\\(((gem)|(torg)|(app))\\$)|(dom.test.com)\\\\
ContentBtnAbort = Abort
ContentBtnCloseStreamsList = Close
ContentBtnCreateQuestion = Copy request for help, to Ops
ContentBtnOpenFolder = Open folder
ContentBtnOpenFolderTT = Open the folder the file is located in
ContentBtnOpenSummary = Open file
ContentBtnPrep = Prepare search
ContentBtnReset = Reset
ContentBtnRunVirusScan = Run a virus scan
ContentBtnSearchExt = Search file extension
ContentBtnSearchExtTT = Search by file extension on Google
ContentBtnSearchFileName = Search filename
ContentBtnSearchFileNameTT = Search the file name on Google
ContentBtnShowFileStreams = View file streams
ContentBtnStartSearch = Start search
ContentCbSetAccountDisabled = Deactivate the account
ContentDgtcStreamsDataSize = Size
ContentDgtcStreamsName = Namn på dataströmmen
ContentLvColumnCreated = Skapad
ContentLvColumnName = Name
ContentLvColumnOwner = Owner
ContentLvColumnSize = Size
ContentLvColumnStreams = Data streams
ContentLvColumnUpdated = Updated
ContentRbAllToolTip = Fetches all files, with changes made in the last 60 days. When searching for all files, it may take significantly longer.
ContentRbLatestToolTip = Fetches the files that have been changed within the last two weeks
ContentRbPrevDateToolTip = Fetches files that have been changed since the specified date
ContentTblCaseNrTitle = Enter case number
ContentTblCbExpandGroups = Expand all file types groups
ContentTblCbGroupExtensions = Group files by file type
ContentTblFileCountTitle = Total number of files:
ContentTblFilterMatch = Files matching specified filter
ContentTblFolderCountTitle = Number of folders scanned:
ContentTblFolderListTitle = Waiting for file list from the following folders
ContentTblGroupInputTitle = Settings
ContentTblGroupSearchSettingsTitle = Search settings
ContentTblGroupSummaryTitle = Summary
ContentTblIdTitle = Enter id for user
ContentTblMDG = Files with multiple dots in the filename (potentially multiple file extensions)
ContentTblMDH = Files in the H folder with multiple dots in the filename (potentially multiple file extensions)
ContentTblO = Folders you do not have access to, add case to Ops
ContentTblPrevDateText = Since the specified date
ContentTblRbAllText = Search all files
ContentTblRbLatestText = Last two weeks
ContentTblStreamsListFileName = File name
ContentTblStreamsListInfo = Alternative data streams for file
ContentTblSummaryTitle = Summary written to:
ContentTblUserTitle = User:
ContentTblValuesTitle = Both values must be specified
ContentTiFilesHeader = All files
ContentTiFilterMatchHeader = Matches filters
ContentTiMDGHeader = Multiple file extensions on G:
ContentTiMDHHeader = Multiple file extensions on H:
ContentTiOHeader = Folders you do not have permissions for
LogScannedFile = Ran a virus scan
LogScannedFileTitle = File name
MsgRecycleBin = The file is in the Recycle Bin and cannot be checked.
StrEnableUser = Should the user account be activated?
StrErrUserNotFound = no user with that id
StrFileOwner = User
StrFileSearchFinished = Finished searching for files
StrGrpDescriptionReplace = for external users
StrGrpDescriptionSplit = Gives Modify on
StrHomeFolder = Home directory
StrLogMsgCaseNr = Case number
StrLogMsgFileSearchAborted = Canceled file search
StrLogMsgFilesMatchingFilterCount = Number of files matching specified filter:
StrLogMsgFilesScannedForVirus = These files have been checked with antivirus
StrLogMsgFilesWithDoubleExtG = Number of files with possibly double file extensions on G:
StrLogMsgFilesWithDoubleExtH = Number of files with possibly double file extensions on H:
StrLogMsgFolderSearch = Searching folders
StrLogMsgId = User ID
StrLogMsgOpenFolder = Opened folder
StrLogMsgOtherPermCount = Number of folders where permissions were missing:
StrLogMsgSearchExt = Searched by file extension
StrLogMsgSearchFileName = Searched by filename
StrLogMsgSearchTime = Search time
StrLogMsgTotNumFiles = Total number of files
StrLogQuestionCopied = Copied
StrLogScriptStart = Start
StrMultiFileVirusSearch = Several files have been selected, which will take longer, the more files selected
StrNoExtension = <No file extension>
StrNoFilesFound = < No files found >
StrOPGettingFiles = Starts fetching files
StrOPGettingFolders = Fetcing folders
StrOPWaitGettingFiles = Awaiting fetching of files
StrOutput1 = Search for potential viruses
StrOutput2 = User
StrOutput3 = Casenumber
StrOutput4 = Total number of files:
StrOutputTimeline1 = Searched: Files updated last two weeks
StrOutputTimeline2 = Searched: Files updated by date
StrOutputTimeline3 = Searched: All available files
StrOutputTitleAllFiles = All files found
StrOutputTitleFilterMatch = These files matched filters
StrOutputTitleFilterMatch2 = Specified filter:
StrOutputTitleFolders = Scanned folders
StrOutputTitleFoldersOtherPerm = Permission missing for the following folders
StrOutputTitleMultiDotG = Multiple File Extensions G:
StrOutputTitleMultiDotH = Multiple File Extensions H:
StrQuestion1 = has reported a possible virus in case
StrQuestion2 = Folders under H:\\ and G:\\ have been examined, but there is no permission for the folders below.
StrQuestion3 = Can you help look at these?
StrQuestionCopied = Text has been copied to the clipboard
StrSepServer = sepser01
StrSepServerFolder1 = APP1$\\Or
StrSepServerFolder2 = APP2\`$\\Or2
StrSepServerFolder3 = APP3$\\Or3
StrUserAccountAlreadyLocked = Account already disabled
StrVerbVirusScan = Search for threats
'@
