ConvertFrom-StringData @'
ContentBtnAbortReport = Abort
ContentBtnSendReport = Send
ContentLblAuthorTitle = Author
ContentLblDescTitle = Description
ContentTblScriptTitle = Select a function or script from the list, write comment and then click "Send"
ContentTblPropHandlerTitle = Select a PropHandler from the list, enter comment, and then click "Send"
ContentTblSuggestionTitle = Suggestion
ContentTBtnSuggestion = Click here to formulate a suggestion
StrBackOfficeMailAddress = backoffice@test.com
StrCodeTypeFunctionTitle = Function
StrCodeTypePHTitle = Property handler
StrCodeTypeToolTitle = Tool
StrFeedbackSubject = Error notification / suggestions from Fetchalon
StrFilePathTitle = Filepath
StrLogAuthorInformed = Developer is informed
StrMessageTitle = Message
StrNewSuggestion = Suggestion for function or tool
StrNewSuggestionDescription = Make a suggestion for a feature or tool that you think is missing
StrNoItemSelected = No function or tool selected in the tree view
StrNotSentToAuthor = Mail not sent to author
StrSentToAuthor = Mail sent to
StrSMTP = smtprelay.test.com
StrSplashAllSent = Messages sent
StrSplashFinished = Thanks for the input
StrSplashToAuthor = Developer informed
StrSuggestionIntro = have the following suggestion
StrSuggestionSubject = Suggestion from Fetchalon
StrToAuthorInfo = Your function/tool in Fetchalon has received a comment/error report/suggestion.
StrToAuthorInfoSentBy = The message was sent by
'@
