ConvertFrom-StringData @'
CodeSysManUri = http://sysman.test.com/
ContentBtnGetAppList = Download list of applications
ContentBtnUninstall = Uninstall
ContentDgLocalInstCol = Installation date
ContentDgLocalNameCol = Application name
ContentDgLocalUserCol = Installed for ...
ContentDgSysManDescCol = Description
ContentDgSysManNameCol = Name
ContentDgWrappersAppNameCol = Name
ContentDgWrappersInstallDateCol = Installation date
ContentDgWrappersProdVerCol = Product version
ContentTblComputerNameTitle = Enter computer name:
ContentTiAppListLocal = Local
ContentTiAppListSysMan = SysMan
ContentTiAppListWrappers = Wrappers
ErrComputerNotFound = No computer was found with the specified name
ErrHiveNotAccessible = Unable to reach registry hive
QUninstall = Sure you want to uninstall
StrAllUsers = All users
StrAppSum = applications
StrDone = Applications uninstalled
StrGetApps = Fetching application list
StrNoDate = No date
StrSwitchComputer = The computer loaded in this tool and the computer sent from the main window are not the same. Do you want to switch to the computer sent from the main window?
StrSwitchComputer2 = Computer from the main window:
StrUninstalling = Uninstalling
TblAppListLocalTitle = This list shows all the applications that are installed on the computer, as well as whether they are installed for a single user or for everyone
TblAppListSysManTitle = This list shows the applications listed in SysMan
TblAppListWrappersTitle = This list shows wrappers installed on the computer
'@
