ConvertFrom-StringData @'
CodeSysManUri = http://sysman.test.com/
CodeWrapperHKey = HKLM:\\SOFTWARE\\Klient\\Wrapper\\
ContentBtnGetAppList = Download list of applications
ContentBtnReset = Reset data
ContentBtnUninstall = Uninstall
ContentDgAppListCoreNameCol = Name
ContentDgLocalInstCol = Installation date
ContentDgLocalNameCol = Application name
ContentDgLocalUserCol = Installed for ...
ContentDgSysManDescCol = Description
ContentDgSysManNameCol = Name
ContentDgWrappersAppNameCol = Name
ContentDgWrappersInstallDateCol = Installation date
ContentDgWrappersProdVerCol = Product version
ContentTblAppListCoreTitle = This list shows the applications included in the Deployment template
ContentTblComputerNameTitle = Enter computer name:
ContentTiAppListCore = Core applications
ContentTiAppListLocal = Local
ContentTiAppListSysMan = SysMan
ContentTiAppListWrappers = Wrappers
ErrComputerNotFound = No computer was found with the specified name
ErrComputerNotReachable = Kan inte nå datorn
ErrHiveNotAccessible = Unable to reach registry hive
ErrSmComputerNotReachable = Problem fetching info from SysMan
QUninstall = Sure you want to uninstall
StrAllUsers = All users
StrAppSum = applications
StrDone = Applications uninstalled
StrGetApps = Fetching application list
StrLogAppInfoFetched = Getting local apps done
StrLogSmInfoFetched = Getting SysMan apps done
StrNoDate = No date
StrSwitchComputer = The computer loaded in this tool and the computer sent from the main window are not the same. Do you want to switch to the computer sent from the main window?
StrSwitchComputer2 = Computer from the main window:
StrUninstalling = Uninstalling
TblAppListLocalTitle = This list shows all the applications that are installed on the computer, as well as whether they are installed for a single user or for everyone
TblAppListSysManTitle = This list shows the applications listed in SysMan
TblAppListWrappersTitle = This list shows wrappers installed on the computer
'@
