ConvertFrom-StringData @'
CodeSysManUri = http://sysman.test.com/
CodeWrapperHKey = HKLM:\\SOFTWARE\\Klient\\Wrapper\\
ContentBtnGetAppList = Download list of applications
ContentBtnReset = Reset data
ContentBtnUninstall = Uninstall
ContentChbGetLocal = Local
ContentChbGetSysMan = SysMan
ContentDgAppListCoreNameCol = Name
ContentDgLocalInstCol = Installation date
ContentDgLocalNameCol = Application name
ContentDgLocalUserCol = Installed for ...
ContentDgSysManDescCol = Description
ContentDgSysManNameCol = Name
ContentDgWrappersAppNameCol = Name
ContentDgWrappersInstallDateCol = Installation date
ContentDgWrappersProdVerCol = Product version
ContentPComputerNotFoundInAdAlertTt = Computer name not found in AD
ContentPComputerNotFoundInSysManAlertTt = Can't find a computer with the specified name in SysMan
ContentTblAppListCoreTitle = This list shows the applications included in the Deployment template
ContentTblComputerNameTitle = Enter computer name:
ContentTiAppListCore = Core applications
ContentTiAppListLocal = Local
ContentTiAppListSysMan = SysMan
ContentTiAppListWrappers = Wrappers
ContenxtTblGetFromTitle = Download list of applications
ErrComputerNotFound = No computer was found with the specified name
ErrComputerNotReachable = Kan inte nå datorn
ErrHiveNotAccessible = Unable to reach registry hive
ErrNoWrapperFound = Could not find specific wrapper, uninstall aborted
ErrSmComputerNotReachable = Problem fetching info from SysMan
ErrSysManUninstall = Problems when uninstalling via SysMan
ErrWrapperUninstall = Problem occurred while uninstalling wrapper:
QUninstall = Sure you want to uninstall
StrAllUsers = All users
StrAppSum = applications
StrDone = Application uninstalled
StrGetApps = Fetching application list
StrInstalledForAll = All
StrLogAppInfoFetched = Getting local apps done
StrLogSmInfoFetched = Getting SysMan apps done
StrNoDate = No date
StrRoleOrg = Org
StrSwitchComputer = The computer loaded in this tool and the computer sent from the main window are not the same. Do you want to switch to the computer sent from the main window?
StrSwitchComputer2 = Computer from the main window:
StrUninstalledWithSysMan = is now scheduled for uninstall via SysMan
StrUninstalling = Uninstalling
StrWrapperUninstallSuccess = Wrapper has been uninstalled
TblAppListLocalTitle = This list shows all the applications that are installed on the computer, as well as whether they are installed for a single user or for everyone
TblAppListSysManTitle = This list shows the applications listed in SysMan
TblAppListWrappersTitle = This list shows wrappers installed on the computer
'@
