ConvertFrom-StringData @'
GetLastWorkstationLoginsNoLogins = No registered logins was found
GetLastWorkstationLoginsParamTitleDate = Date
GetLastWorkstationLoginsParamTitleName = Name
GetO365AccountStatusCodeMsExchIgnoreOrg = OU=Org2
GetO365AccountStatusNotConnected = Not connected to O365 services
GetO365AccountStatusParamADActiveCheck = AD Active
GetO365AccountStatusParamADActiveFalse = Not active
GetO365AccountStatusParamADLockCheck = AD unlocked
GetO365AccountStatusParamADLockFalse = The account is locked
GetO365AccountStatusParamADMailCheck = Email attribute specified
GetO365AccountStatusParamADMailFalse = Email attribute not specified
GetO365AccountStatusParamADmsECheck = msExchMailboxGuid is empty
GetO365AccountStatusParamADmsEFalse = msExchMailboxGuid not empty
GetO365AccountStatusParamCheck = Available in AD
GetO365AccountStatusParamOAccountCheck = O365 account created
GetO365AccountStatusParamOAccountFalse = O365 account not created
GetO365AccountStatusParamOExchCheck = Synced to Exchange
GetO365AccountStatusParamOExchFalse = Not synced to Exchange
GetO365AccountStatusParamOLicCheck = Has E3 license
GetO365AccountStatusParamOLicFalse = Does not have an E3 license
GetO365AccountStatusParamOLicFalseWrongOrg = Org is not assigned to E3
GetO365AccountStatusParamOLoginCheck = O365 login active
GetO365AccountStatusParamOLoginFalse = Login disabled
GetO365AccountStatusParamOMigCheck = Member of O365-MigPilot
GetO365AccountStatusParamOMigFalse = Not a member
GetO365AccountStatusParamTitleType = Check
GetO365AccountStatusParamTitleValue = Status
GetO365AccountStatusValOk = OK
GetSharedAccountsByDepIdAdSearchBasePrefix = ou=Custom,ou=Users,ou=
GetSharedAccountsByDepIdAdSearchBaseSuffix = ,ou=Dep,dc=Domain,dc=DC
GetSharedAccountsByDepIdDepAdProp = ADPropName
GetSharedAccountsByDepIdNoAccounts = No accounts found
GetSharedAccountsByDepIdObjClass = ADObjClass
GetSharedAccountsByDepIdOrgRegex = (Org0|Org1|Org2)
GetSharedAccountsByDepIdPropTitleActive = Active account
GetSharedAccountsByDepIdPropTitleComputer = At computer
GetSharedAccountsByDepIdPropTitleDepId = Costcenter
GetSharedAccountsByDepIdPropTitleName = Shared account
GetSharedAccountsByDepIdPropTitlePwdExpDate = Password expiration date
GetSharedAccountsByDepIdPropTitlePwdExpDateLong = days, report to Op
GetSharedAccountsByDepIdPropTitlePwdExpDateNo = Does not expire
GetSharedAccountsByDepIdPropTitlePwdLocked = Locked due to bad password
GetSharedAccountsByDepIdPropTitleType = Accounttype
GetSharedAccountsByDepIdPropValNo = No
GetSharedAccountsByDepIdPropValYes = Yes
RemoveProfileVKNotValidOrg = The organization does not use vClient
RemoveProfileVKProfileRemoved = The Client profile has now been removed
RemoveProfileVKQuestion = What organization do the user work in?
RemoveProfileVKQuestionReturn = Folder opened in Explorer
RemoveProfileVKQuestionTitle = Enter organization
RemoveProfileVKTCSelectCustomer = Could not make out organization, for which organization should the profile be cleared?
RemoveProfileVKTCSelectCustomerTitle = Select organization
StrCompareUserGroupsNoValidUsers = Not enough users to compare
StrGetFolderMembershipPropCodeNotMatch = .*_App_Office(key|_Templates).*
StrGetFolderMembershipPropCodeReplace1 = \\\\\\\\dfs\\\\gem\\$
StrGetFolderMembershipPropCodeReplace2 = \\\\\\\\dfs\\\\org2\\$
StrGetFolderMembershipPropCodeSplit1 = on
StrGetFolderMembershipPropTitleFolder = Folder
StrGetFolderMembershipPropTitleGroup = AD-group
StrGetFolderMembershipPropTitlePermission = Permission type
StrGetFolderMembershipPropValRead = Read
StrGetFolderMembershipPropValWrite = Write
SysManServerUrl = http://sysman.test.com/
'@
