ConvertFrom-StringData @'
ClearCcmExecDone = Tasklistan för CcmExec har nu rensats
ClearCcmExecErr = Fel uppstod
ClearCcmExecErrService = Fel uppstod när service skulle startas om
ClearDNSCacheDone = Cache har rensats
ClearNetIdCacheFinished = Tog bort följande filer:
CloseCurrentOpenRemoteConnectionsSuccess = Remote service omstartad
GetLastBootUpTimeNoData = Ingen dator hittades
GetLastBootUpTimeNoDateInfo = Kan ej nås
GetLastBootUpTimePropDateInfoTitle = Senaste uppstart
GetLastBootUpTimePropNameTitle = Datornamn
GetLastBootUpTimePropSMTitle = Senaste datum från SysMan
GetLastLoggedInErrNoUser = Användare hittas inte i AD
GetLastLoggedInStrCompNotFound = Datornamn hittas inte i SysMan
GetLastLoggedInStrCompTitle = Datornamn
GetLastLoggedInStrUserTitle = Användare
OpenWebPageStrDone = Websida öppnad
RepairCmAgentStrDone = CM Agenten har nu återställts
RepairO365LicensStrCimError = Fel uppstod med anslutningen
RepairO365LicensStrDone = Skriptet för reparation av Office-licenser har nu avslutats
RepairO365LicensStrError = Fel uppstod
ResetHostsFileFinished = Host fil rensad
ResetOutlookNavigationPanelFinished = UI återställt
ResetOutlookViewsFinished = Vyer återställda
RestartSMSCMAgentStrDone = CM Agenten har nu startats om
SendToastSuccess = Meddelande skickat
StartCMAllMeasuresDone = Alla scheman har nu initierats i CM Agenten
StartCMAllMeasuresErrScheduling = Fel uppstod med följande scheman
StartCMAppRefreshDone = Alla scheman för kontroll av applikationer har nu initierats i CM Agenten
StartCMAppRefreshErrScheduling = Fel uppstod med följande scheman
StartCMNewApplicationsDone = Sökning för nya utskjutningar av applikationer har starts
StartCMNewApplicationsErr = Fel uppstod
StrAppId = Meddelande från Servicedesk
StrSameCostCenterPropName = CcPropName
SysManServerUrl = http://sysman.test.com/
'@
