ConvertFrom-StringData @'
ContentBtnSet = Spara autoreply
ContentCbActivate = Aktivera autoreply
ContentCbCreateOOFEvent = Skapa händelse i kalendern?
ContentCbDeclineAllEventsForScheduledOOF = Avböj även befintliga händelser under perioden
ContentCbDeclineAllEventsForScheduledOOFTT = Detta kommer ta bort händelserna från kalendern. Är användaren organisatör, kommer händelsen också tas bort för inbjudna användare.
ContentCbDeclineEventsForScheduledOOF = Avböj existerande möten under perioden?
ContentCbDeclineRequests = Avböj mötesinbjudningar
ContentCbScheduled = Sätt ett slutdatum
ContentCbSendExternal = Skicka till mottagare utanför organisationen?
ContentGbEnd = Slutdatum för autoreply
ContentGbExternalAutoReply = Meddelande utanför organisationen
ContentGbInternalAutoReply = Meddelande inom organisationen
ContentGbStart = Startdatum för autoreply
ContentRbExternalReplyAll = Alla
ContentRbExternalReplyContacts = Endast kontakter
ContentTblDeclineMeetingMessageTitle = Meddelande när mötesinbjudning avböjs
ContentTblFoundUserTitle = Hittat konto:
ContentTblIdTitle = Ange id eller mailadress
ContentTblOOFEventSubjectTitle = Händelserubrik
ContentTbSummaryTitle = Summering, dessa inställningar kommer sättas när du trycker på "Spara autoreply"
LogSummary = Satte följande inställningar för autoreply
StrAllRequestsIsDeclined = Befintliga händelser kommer tas bort
StrDisableAutoReply = Inaktiverar autoreply
StrDontSendExternal = Skickar inte externt
StrNoO365User = Inget användarkonto i Office365 hittades
StrNoUser = Ingen användare hittades
StrOOFEventIsCreated = En händelse kommer skapas i kalendern
StrRequestsIsDeclined = Inbjudningar under perioden kommer nekas
StrScheduledAutoReplyNotSet = Start och slutdatum måste sättas för att kunna använda denna inställning
StrSendExternalAll = alla
StrSendExternalOnlyContacts = enbart kontakter på kontot
StrSendExternalStart = Skickar externt till
StrSetAutoReplyNotScheduled = Autoreply är aktivt utan slutdatum
StrSetAutoReplyScheduled = Autoreply schemaläggs från 
StrSetAutoReplyScheduledManualEnd = tills det manuellt inaktiveras (slutdatum satt till 5 år framåt)
StrSetAutoReplyScheduleEnd = fram till
StrSetAutoReplyStart = Sätter autoreply att skickas
StrSetting = Arbetar
StrSettingDone = Autoreply inställt
StrSettingInactiveDone = Autoreply inaktiverat
'@
