ConvertFrom-StringData @'
CodeSysManUrl = https://sysman.test.com/sysman
ContentBtnPerform = Utför
ContentBtnRefetchGroups = Läs in grupper igen
ContentBtnRefetchGroupsTT = Läs in grupperna igen
ContentBtnUndo = Avbryt
ContentTblAddedUsersTitle = Tillagd behörighet
ContentTblApp = Välj applikation
ContentTblAppGroupList = Välj app-grupp genom att dubbelklicka
ContentTblComputerTitle = Dator som behöver AD-grupp
ContentTblGroupsChosen = Valda app-grupper
ContentTblLog = Utförda ändringar
ContentTblUsersAddPermission = Skapa behörighet
ContentTblUsersRemovePermission = Ta bort behörighet
ContentWindowTitle = Ta bort/lägg till app-behörigheter
ErrMessageGetAppGroups = Hämtning av appgrupper
ErrMessageGetUser = Hämta användare
ErrMessageSetPassword = Sätta lösenord
ErrMessageSetSettings = Ställ in inställningar
ErrScriptPermissions = Du saknar nödvändiga rättigheter för att köra detta skript
ErrSysManGenError = Fel vid kontakt med SysMan
ErrSysManNoComputer = Dator hittas inte i SysMan
ErrSysManNoSystem = System hittas inte i SysMan
ErrUserNotFound = NotFound
LogInputAdd = För tillägg:
LogInputRemove = För borttag:
LogMessageAdd = Har fått behörighet:
LogMessageAddComputer = Dator fått AD-grupp:
LogMessageRemove = Tagit bort behörighet:
MsgAddComputer = Datorer som fått AD-grupp:
MsgMessageIntro = Har utfört nedan ändringar till följande
MsgNew = Ny behörighet
MsgNewPassword = nytt lösenord
MsgNoAccount = Hittade inget konto för följande
MsgRemove = Ta bort behörighet
QCont1 = Vill du för
QCont2 = utföra
QCont3 = ändringar
QContErr = Vissa användare har inte AD-konton
QContTitle = Fortsätta
StrBORoleGrp = Rol_Servicedesk_Backoffice
StrSDRoleGrp = Rol_Servicedesk
StrDuplicates = Det finns dubbletter av värden i listorna. Rätta till dessa och kör igen
StrDuplicatesTitle = Dubbletter
StrErrorUsersTitle = ID saknas i AD
StrFinishMessage = ändringar gjorda. Ett lösningsmeddelande har kopierats till clipboard
StrFinishMessageTitle = Klar
StrGetADGroups = Hämtar app-grupper...
StrGettingComputers = Hämtar datorer
StrGettingUser = Hämtar användare
StrGroupsTitle = Grupper
StrLogMessage = Applikation
StrLogOut = För att behörigheten ska börja gälla, behöver kontot loggas ut och sedan in igen.
StrOpGrp = Rol_Katalog_Drift
StrOpLogPath = \\\\domain.test.com\\FolderTool
StrPreparing = Förbereder...
StrProgressTitle = Tillämpar gruppbehörigheter
StrRemovedUsersTitle = Behörighet borttagen
StrSigGen = Med vänliga hälsningar
StrSigSD = Servicedesk
StrSigSD2 = Org2
StrSpecAddIntroApp3 = Tack för din beställning, du har nu fått tillgång till:
StrSpecAddOutroApp3 = Inloggning krävs för att komma åt sidan
StrSpecOrg = org6
StrSpecRemIntroApp3 = Behörighet har nu tagits bort för
'@
