ConvertFrom-StringData @'
ContentBtnAbortImport = Avbryt
ContentBtnAddFunctionForExtraction = Lägg till för extraktion
ContentBtnAddHotkeyForExtraction = Lägg till för extraktion
ContentBtnAddHotstringForExtraction = Lägg till för extraktion
ContentBtnAddHsOption = Lägg till inställning
ContentBtnAddNew = Lägg till
ContentBtnAddVariableForExtraction = Lägg till för extraktion
ContentBtnCancelExtraction = Avbryt extraktion
ContentBtnCancelNew = Avbryt
ContentBtnDeselectAll = Avmarkera alla
ContentBtnExtractToBackup = Extrahera till backup fil
ContentBtnExtractToScript = Extrahera till skriptfil
ContentBtnFunctionAddParameter = Lägg till parameter
ContentBtnFunctionRemove = Ta bort funktion
ContentBtnFunctionSave = Spara funktion
ContentBtnHotkeyRemove = Ta bort
ContentBtnHotkeySave = Spara
ContentBtnHotstringRemove = Ta bort Hotstring
ContentBtnHotstringSave = Spara Hotstring
ContentBtnInsertExistingCommentForExtraction = Använd samma kommentar
ContentBtnReadFileToImport = Läs in fil
ContentBtnRemoveFromExtractList = Ta bort markerad från extraktionslistan
ContentBtnSave = Spara till fil
ContentBtnSelectAll = Markera alla
ContentBtnSelectFileToImport = Välj fil
ContentBtnStartImport = Starta import
ContentBtnVariableRemove = Ta bort variabel
ContentBtnVariableSave = Spara variabel
ContentBtnWriteToOtherLocation = Skriv till angiven plats
ContentChbImpComment = Importera
ContentChbImpFunctionsSelectAll = Välj alla
ContentChbImpFunctionsSelectAllDeselected = Avmarkera alla
ContentChbImpHotkeysSelectAll = Välj alla
ContentChbImpHotkeysSelectAllDeselected = Avmarkera alla
ContentChbImpHotstringsSelectAll = Välj alla
ContentChbImpHotstringsSelectAllDeselected = Avmarkera alla
ContentChbImpSettingsSelectAll = Välj alla
ContentChbImpSettingsSelectAllDeselected = Avmarkera alla
ContentChbImpVariablesSelectAll = Välj alla
ContentChbImpVariablesSelectAllDeselected = Avmarkera alla
ContentExpHotstringOptions = Inställningar
ContentExpParameters = Parametrar
ContentGbSettingsFiles = Inställningar för fil till annan plats
ContentGbSettingsScriptOperations = Skripthantering
ContentGbSettingsScriptSettings = Skriptformatering
ContentLblAdvancedHotstringTitle = Ska denna Hotstring var avancerad
ContentLblExtractCommentTitle = Kommentar för extraherat skript
ContentLblExtractListTitle = Saker som ska extraheras
ContentLblFileToImportTitle = Fil att importera
ContentLblFunctionCodeTitle = Kod i funktionen
ContentLblFunctionCommentTitle = Kommentar
ContentLblFunctionHeaderTitle = Så här kommer functionshuvudet se ut i koden:
ContentLblFunctionNameTitle = Funktionsnamn
ContentLblFunctionsListTitle = Funktionslista
ContentLblHotkeyCodeTitle = Kod
ContentLblHotkeyCommentTitle = Kommentar
ContentLblHotkeyHotkeyTitle = Hotkey kombination
ContentLblHotkeyModifierDisplayTitle = Visa modifier ...
ContentLblHotkeyNameTitle = Namn
ContentLblHotkeysTitle = Hotkeys
ContentLblHotstringCodeTitle = Kod som ska köras
ContentLblHotstringCommentTitle = Kommentar
ContentLblHotstringMenuItemTitle = Titel i meny
ContentLblHotstringNameTitle = Namn på Hotstring
ContentLblHotstringSystemsListTitle = System
ContentLblHotstringSystemTitle = System Hotstring är kopplat till
ContentLblNewNameTitle = Namn
ContentLblNewSystemTitle = System
ContentLblVariableCommentTitle = Kommentar
ContentLblVariableListTitle = Variabellista
ContentLblVariableNameTitle = Namn
ContentLblVariableValueTitle = Värde
ContentMenuItemNewCommand = Skapa ny ...
ContentMenuItemNewFunction = Funktion
ContentMenuItemNewHotkey = Hotkey
ContentMenuItemNewHotstring = Hotstring
ContentMenuItemNewVariable = Variabel
ContentRbHotkeyModifierDisplayCode = Kod
ContentRbHotkeyModifierDisplayName = Namn
ContentRbVariableAsExpression = Expression (uttryck)
ContentRbVariableAsExpressionTt = Variabeln kommer använda ':=' för att definiera värdet. Värdet behöver använda citationstecken (") för att definiera en sträng.
ContentRbVariableAsLegacy = Legacy
ContentRbVariableAsLegacyTt = Variabeln kommer använda lika-med-tecken för att definiera värdet. Värdet behöver inte använda citationstecken (") för att definiera en sträng.
ContentTblBackupExtractionTargetTitle = Extraherade objekt kommer skrivas till backupfil här:
ContentTblCommentToImportTitle = Kommentar
ContentTblFunctionsToImportTitle = Funktioner
ContentTblHotkeyToImportTitle = Hotkeys
ContentTblHotstringToImportTitle = Hotstrings
ContentTblScriptCommentTitle = En kommentar som placeras i början av skriptfilen. Detta kan t.ex. vara en förklaring vad skriptet gör eller vad den har för syfte.
ContentTblScriptExtractionTargetTitle = Extraherade objekt kommer skrivas till skriptfil här:
ContentTblSettingsToImportTitle = Inställningar
ContentTblVariablesToImportTitle = Variabler
ContentTiFunctions = Funktioner
ContentTiHotkeys = Hotkeys
ContentTiHotstringsHeader = Hotstrings
ContentTiImport = Importera
ContentTiScriptComment = Skript kommentar
ContentTiSettings = Inställningar
ContentTiToExtract = Att extrahera
ContentTiVariables = Variabler
ContentTtBtnSave = Skriver alla objekt till en skriptfil enligt filinställningar under "Inställningar". Både skriptfil och backupfil kommer skrivas.
ContentTtGbSettingsFilesInfo = Detta definierar värden för placering, samt namn på fil som kan skrivas till annan plats än hemkatalog för nuvarande handläggare.
ContentTtGbSettingsScriptOperationsInfo = Dessa inställningar styr hur skriptet körs och vad det ska innehålla.
ContentTtGbSettingsScriptSettingsInfo = Dessa inställningar definierar hur sektioner i skriptfilen ska särskiljas.
ContentTtGridNewSystemInfo = Välj ett redan registrerat system, eller ange ett nytt
ContentTtLblHotstringCodeCharLimit = Med inställningen Send Mode > SendInput, begränsas texten till 5000 tecken. Detta är en begränsning på operativsystem nivå.
ContentTtSettingsImpWarning = Varje inställning som blir importerad kommer skriva över redan angivna inställningar. Importera bara inställningar om du är säker på att dessa värden önskas.
ContentTtTiToExtractIsDisabled = Inga objekt tillagda för extrahering.
ErrBackupPathNotValid = Den angivna mappen för backup är inte en giltig sökväg.
ErrFuncParamNameExists = En annan parameter har samma namn
ErrFunctionNameExists = En annan funktion har redan det namnet
ErrHotkeyNameExists = Namnet används redan
ErrHotstringMenuTitleExists = En annan Hotstring har samma text som MenuTitle. Detta kan leda till förvirring vilken som ska köras från menyn.
ErrHotstringNameExists = En annan Hotstring har redan det namnet
ErrImpFileInvalidExtention = Den angivna filen är inte av rätt typ. Endast XML och JSON kan användas
ErrImpFileNotFound = Den angivna sökvägen är felaktig, hittar ingen fil på den adressen
ErrImpFunctionNameExists = Namnet används av existerande funktion
ErrImpHotkeyHotkeyExists = Hotkey knapp-kombination används av annan Hotkey
ErrImpHotstringNameExists = Namnet används av existerande Hotstring
ErrImpInfoJsonNotCorrectFormated = JSON-filen verkar inte vara formaterad på korrekt sätt
ErrImportFailedSummary = Vissa importer utfördes inte, se tooltip per objekt
ErrImpVariableNameExists = Namnet används av existerande variabel
ErrNewObjectNameContainsNonWordChar = Namnet får endast innehålla bokstäver och siffror
ErrNewObjectNameContainsWhiteSpaceChar = Namnet får inte innehålla 'whitespace' tecken
ErrNewObjectNameExists = Namnet används redan
ErrScriptPathNotValid = Den angivna mappen för skript är inte en giltig sökväg.
ErrSettingUserIdNotFound = Hittar ingen användare med det id:t
ErrVariableNameExists = En annan variabel har redan detta namn
StrAhkDataRead = Ordinarie fil för AhkData har lästs in.
StrDefaulFuncCode = ; Lägg in funktionskoden här
StrDefaultMenuTitle = Menyrad för
StrExtractionCleared = Alla objekt borttagna från extraheringslistan
StrExtractionObjectRemoved = borttaget från extraheringslistan
StrFunctionNameContainsWhitespace = Namn på funktion får inte innehålla mellanslag, tab eller annan whitespace-tecken.
StrHkTtAlt = Alt-knapp ; Aktivera när en Alt-knapp hålls nedtryckt, om inte '<' eller '>' också anges.
StrHkTtAltGr = AltGr-knappen ; Aktivera när AltGr-knappen hålls nedtryckt.
StrHkTtAmpCustComb = Kombinera hotkeys ; Kombinera knappar som vanligtvis inte är modifiers, t.ex. an bokstav, och använd som modifier.
StrHkTtCtrl = Control-knapp ; Aktivera när en Control-knapp hålls nedtryckt, om inte '<' eller '>' också anges.
StrHkTtLeftAlt = Vänstra knappen av parvarianten ; Använd enbart den vänstra varianten av knapp det finns ett par av, så som Control-, Alt- eller Shift-knapparna.
StrHkTtRightAlt = Högra knappen av parvarianten ; Använd enbart den högra varianten av knapp det finns ett par av, så som Control-, Alt- eller Shift-knapparna.
StrHkTtShift = Shift-knappen ; Aktivera när en Shift-knapp hålls nedtryckt, om inte '<' eller '>' också anges.
StrHkTtTilde = Blockera ej ordinarie funktion ; Vanligtvis blockeras ordinarie funktion för att köra en hotkey. Med tilde kommer funktionen köras som normalt.
StrHkTtUp = När knappen släpps upp ; Aktivera när knapparna släpps upp
StrHkTtWildcard = Acceptera alla modifiers ; Aktivera hotkeyn oavsett om en eller flera modifiers har angivits.
StrHkTtWin = Windows-knappen ; Aktivera när Windows-knappen hålls nedtryckt.
StrHotstringDefaultText = Ange text eller AHK-kod för denna hotstring här
StrHotstringNameContainsWhitespace = Namnet får inte innehålla mellanslag, tab eller annan whitespace-tecken.
StrHsExtractedIncFun = -funktionen används, har inkluderats för extrahering
StrHsOptionAsterix = En avslutande karaktär (t.ex. mellanslag, punkt eller Enter) krävs inte för att aktivera Hotstring. Aktivering sker direkt när sista tecknet i namnet skrivs.
StrHsOptionB0 = Ingen automatisk radering av Hotstring-label
StrHsOptionC = Känslig för gemen/versal
StrHsOptionC1 = Följer inte skriven gemen/versal från Hotstring-label. Använd det här alternativet för att Auto-Replace Hotstring inte ska följa gemen/versal och förhindra att de överensstämmer med de karaktärer du faktiskt skriver. Fallkonformerande Hotstrings (som är standard) producerar sin ersättningstext i versaler om du skriver förkortningen i versaler. Om du skriver den första bokstaven som versal kommer den första bokstaven i ersättningen också vara versal (om det är en bokstav). Om du skriver på något annat sätt skickas ersättningen exakt som definierat.
StrHsOptionKn = Fördröjning mellan skrivande av tecken i ersättningstexten. Ange fördröjning (i millisekunder), t.ex. K10 anger fördröjning i 10 millisekunder, K-1 anger ingen fördröjning. Inställningen är direkt beroende av vilket 'Send Mode' som är aktivt: 'SendInput' - fördröjning ignoreras, 'SendPlay' - standardfördröjning är noll, fördröjning sker mellan simulerad knapptryckning ned och att knappen släpps, 'SendEvent' - Noll rekommenderas för de flesta ändamål eftersom det är snabbt, men samarbetar fortfarande bra med andra processer. Ange K-1 för att inte ha någon försening alls, vilket är användbart för att göra auto-ersättningar snabbare om din CPU ofta är under tung belastning. När det är inställt på -1 blir ett skripts processprioritering en viktig faktor i hur snabbt det kan skicka tangenttryckningar.
StrHsOptionO = Utelämna den avslutande karaktären av Auto-Replace Hotstrings när ersättningen görs. Detta är användbart när du vill att en Hotstring ska hållas otvetydig genom att fortfarande kräva en slutande karaktär, men inte faktiskt vill att slutkaraktären ska visas på skärmen. Till exempel, om ':O:ar::aristokrat' är en hotstring, att skriva "ar" följt av mellanslag kommer att producera "aristokrat" utan extra mellanrums-tecken, vilket gör att du kan göra ordet pluralis eller besittande utan att behöva trycka på backspace.
StrHsOptionPn = Processprioritet för Hotstring, har ingen effekt för automatiska ersättnings Hotstrings.
StrHsOptionQuestionMark = Aktivering sker även fast namnet skrivs inuti ett annat ord.
StrHsOptionR = Skicka text som rå text, dvs utan att tolka t.ex. {Enter} som att skicka ett tryck på Enter-tangenten
StrHsOptionSE = Send mode 'SendEvent'. Gammal metod från innan AutoHotKey version 1.0.43.
StrHsOptionSI = Send mode 'SendInput'. Är vanligtvis snabbaste Send Mode. Hindrar annan input från tangentbord och mus från att störa en Hotstrings auto-ersättning.
StrHsOptionSP = Send mode 'SendPlay'. Skickar tecken som meddelande till appliktionen, istället för att simulera knapptryckningar.
StrHsOptionT = Text mode, alla tecken tolkas som text och de försöker inte tolkas som kommandon, med undantag för `r, `n, `t och `b
StrHsOptionX = Hotstring används för att köra kommando istället för auto-ersättning.
StrHsOptionZ = Återställer Hotstring-igenkänningen efter varje aktiveing. Med andra ord kommer skriptet att börja vänta på en helt ny Hotstring, ignorera från övervägande allt du tidigare skrev. Detta kan förhindra oönskad aktivering av Hotstrings. Som exempel, med Hotstring ':b0*?:11::', om du skriver tre ettor (1) skulle aktivera Hotstring två gånger, eftersom den mellersta ettan båda agerar som sista tecknet vid första aktiveringen, och som första tecknet i sista aktiveringen. Med inställning 'Z' framför 'B0', behöver fyra ettor skrivas för att aktivera Hotstring två gånger.
StrImpDupPrefixFunctions = Funktioner
StrImpDupPrefixHotkeys = Hotkeys
StrImpDupPrefixHotstrings = Hotstring
StrImpDupPrefixVariables = Variabler
StrImpFileFilterDesc = Gamla och nya data-filer
StrImpFinishedMsg = Filen har lästs in. Antal objekt som hittades:
StrImpInfoExcludedItems = Inställningar och changelog ignoreras under importen
StrImportDuplicates = Dessa är dubbletter och har inte lästs in från ordinariefil:
StrInfoNoPathsSelected = Mapp för skrivning av filer har inte valts
StrScriptFileTitle = Denna fil skapades
StrScriptTextAutoUpdated = Skriptet har automatiskt lästs in på nytt
StrSettingBackupPathName = Sökväg för backupfil
StrSettingBackupPathTtInfo = Den plats där backupfilen ska placeras
StrSettingFileNameName = Filnamn
StrSettingFileNameTtInfo = Basnamn för backup- och skriptfilerna. Respektive fil får sedan tillhörande filändelse.
StrSettingIncludeAutoUpdateName = Inkludera autoupdate
StrSettingIncludeAutoUpdateTtInfo = Inkludera kod i skriptfilen som automatiskt laddar om skriptet om filen uppdateras.
StrSettingMenuShowTriggerName = Menytrigger
StrSettingMenuShowTriggerTtInfo = Text som ska föregå systemnamn för att trigga att menyn visas
StrSettingResetDefault = Återställ standardvärde
StrSettingSaveWithGuiName = Inkludera GUI för menyn
StrSettingSaveWithGuiTtInfo = Ska skriptfilen inkludera kod för att skapa GUI? Med detta menas att det för varje system kommer skapas en meny som visas när menytriggern tillsammans med namnet på systemet skrivs.
StrSettingScriptPathName = Sökväg för skriptfil
StrSettingScriptPathTtInfo = Den plats där skriptfilen ska placeras
StrSettingSelectFolder = Välj en mapp
StrSettingTitleDividerCharacterName = Tecken för titelavgränsning
StrSettingTitleDividerCharacterTtInfo = Tecken som grupperas med grupptitel i skriptfilen. Detta för att enklare visa gruppering
StrSettingTitleForFunctionsName = Titel för funktioner
StrSettingTitleForFunctionsTtInfo = Titeltext i skriptfil för att indikera grupp för definition av funktioner
StrSettingTitleForHotkeysName = Titel för Hotkeys
StrSettingTitleForHotkeysTtInfo = Titeltext i skriptfil för att indikera grupp för definition av Hotkeys
StrSettingTitleForHotstringsName = Titel för Hotstrings
StrSettingTitleForHotstringsTtInfo = Titeltext i skriptfil för att indikera grupp för definition av Hotstrings
StrSettingTitleForMenuName = Titel för meny
StrSettingTitleForMenuTriggersName = Titel för menytriggers
StrSettingTitleForMenuTriggersTtInfo = Titeltext i skriptfil för att indikera grupp av menytriggers
StrSettingTitleForMenuTtInfo = Titeltext i skriptfil för att indikera grupp för definition av menyer
StrSettingTitleForVariablesName = Titel för variabler
StrSettingTitleForVariablesTtInfo = Titeltext i skriptfil för att indikera grupp för definition av variabler
StrSettingUserIdFoundPrefix = Hittade
StrSettingUserIdName = Användar-id
StrSettingUserIdTtInfo = Id för mottagare av skriptfil. Filen kommer placeras i användarens H:
StrSystemNameContainsWhitespace = Namn på system får inte innehålla mellanslag, tab eller annan whitespace-tecken.
StrVariableNameContainsWhitespace = Namn på variabel får inte innehålla mellanslag, tab eller annan whitespace-tecken.
StrWroteBackupFile = Skrev backup fil till
StrWroteScriptFile = Skrev skript fil till
'@
