ConvertFrom-StringData @'
ContentBtnLoadCase = Läs in ärendeinfo
ContentBtnRemoveCaseInfo = Radera ärende-fil
ContentBtnReset= Rensa data
ContentBtnSaveCase = Spara
ContentCbCategoryList = < Välj >, System, Säkerhet, Klient, Skrivare, Telefoni, Trådat nätverk, Trådlöst nätverk, Övrigt
ContentCbOrderedArticleList = < Välj >, Annan artikel, Användarsupport, Generell tjänsteförfrågan, Tjänstekatalog, Hänvisning, Icke standard Tjänstekatalog, Klagomål, Kontobeställning, Kontohantering, Kostnadsartikel, Nytt lösenord, Övrigt
ContentCbSubCategoryKlient = < Välj >, Diskutrymme, Inloggning, Applikation saknas, Applikationsinstallation, Hårdvara, Kringutrustning, Prestanda
ContentCbSubCategorySkrivare = < Välj >, Inställningar, Hårdvarufel, Skrivare saknas på dator
ContentCbSubCategorySystem = < Välj >, Behörighet, Inloggning, Applikationen startar inte, Applikationen ej tillgänglig, Långa svarstider, Funktion fungerar inte
ContentCbSubCategorySäkerhet = < Välj >, Virus, Phishing, Annan säkerhetsincident
ContentCbSubCategoryTelefoni = < Välj >, Samtal, Hårdvara, Mobildata, Fax
ContentCbSubCategoryTrådat_nätverk = < Välj >, Saknar anslutning, Tappar anslutning, Långsamt nätverk, Trasigt nätverksuttag
ContentCbSubCategoryTrådlöst_nätverk = < Välj >, Saknar anslutning, Tappar anslutning, Långsamt nätverk, Dålig täckning
ContentCbSubCategoryÖvrigt = < Välj >, Övrigt
ContentCbWayOfContactList = < Välj >, Telefon, Personlig kontakt
ContentGbOrdererInfo = Info Beställare
ContentGbUserInfo = Info Användare
ContentLblCaseEndMessageTitle = Lösningsmeddelande
ContentLblCategoryTitle = Kategori
ContentLblComputerNameTitle = Datornamn
ContentLblConfigObjTitle = Konfigurationsobject
ContentLblConfigObjTitleTT = cmdb_ci
ContentLblDescTitle = Ärendebeskrivning
ContentLblInternalAddressTitle = Internadress
ContentLblIpAddressTitle = IP-adress
ContentLblNetworkSocketTitle = Nätverksuttags
ContentLblOrderedArticleTitle = Beställd artikel
ContentLblOrdererIdTitle = Id
ContentLblOrdererMailInvalid = Mailadress ej giltigt
ContentLblOrdererMailTitle = Mailadress
ContentLblOrdererTelephoneInvalid = Telefonnummer ej giltigt
ContentLblOrdererTelephoneTitle = Telefonnummer
ContentLblPrinterQueueTitle = Skrivarkö
ContentLblServiceTitle = Tjänst
ContentLblServiceTitleTT = business_service
ContentLblSubCategoryTitle = Underkategori
ContentLblTitleTitle = Rubrik
ContentLblUserIdTitle = Id
ContentLblUserIdInvalid = Id ej giltigt
ContentLblOrdererIdInvalid = Id ej giltigt
ContentLblUserMailInvalid = Mailadress ej giltigt
ContentLblUserMailTitle = Mailadress
ContentLblUserTelephoneInvalid = Telefonnummer ej giltigt
ContentLblUserTelephoneTitle = Telefonnummer
ContentLblWayOfContactTitle = Kontaktväg
ContentLblWorklogTitle = Arbetslog
ContentTBtnInc = INC
ContentTBtnRitm = RITM
StrJsonFileName = CM backup data
StrSaveTo = Data sparat till
StrSelectCase = < Välj ärendeinfo-fil >
'@
