ConvertFrom-StringData @'
CodeRegKbSummaryReqAdGrps = (Rol_SD_Backoffice)|(Rol_SD_OpRes)
ContentBtnCheckForUpdates = Sök efter uppdateringar
ContentBtnClearErrorLogSearch = Avbryt sök
ContentBtnClearLogSearch = Avbryt sök
ContentBtnCopyErrorInfo = Kopiera information
ContentBtnCopyLogInfo = Kopiera
ContentBtnCopyRollbackInfo = Kopiera lista
ContentBtnCreateCodeTemplate = Skapa kodmall
ContentBtnCreateKdSummary = Skapa sammanfattning till KB
ContentBtnDiffCancel = Avbryt
ContentBtnDoRollback = Rulla tillbaka filversion
ContentBtnErrorLogSearch = Sök
ContentBtnFuncAddInputVariable = Ny variabel
ContentBtnFuncAddInputVariableBool = Ny variabel
ContentBtnFuncAddInputVariableList = Ny variabel lista
ContentBtnFuncAddSettingTitle = Lägg till inställning
ContentBtnListRollbacks = Lista rollbacks
ContentBtnLogSearch = Sök
ContentBtnOpenErrorLog = Öppna fellogg
ContentBtnOpenFailed = Öppna
ContentBtnOpenOutputFile = Öppna fil
ContentBtnOpenPopupCopyLogInfo = Kopiera info
ContentBtnOpenRollbackFile = Öppna fil
ContentBtnPHAddSettingTitle = Lägg till inställning
ContentBtnReadErrorLogs = Läs in felloggar
ContentBtnReadErrorLogsAgain = Läs in felloggar (igen)
ContentBtnReadLogs = Läs in loggar
ContentBtnReadLogsAgain = Läs in loggar (igen)
ContentBtnResetTemplateInfo = Återställ
ContentBtnToolAddSettingTitle = Lägg till inställning
ContentBtnUpdatedInProdOpenBothFiles = Öppna båda filerna
ContentBtnUpdatedInProdOpenDevFile = Öppna Dev-fil
ContentBtnUpdatedInProdOpenDiffs = Öppna diff-fönster
ContentBtnUpdatedInProdOpenProdFile = Öppna Prod-fil
ContentBtnUpdateFailedScripts = Uppdatera checkade filer
ContentBtnUpdateScripts = Uppdatera markerade filer
ContentBtnUpdatesOpenBothFiles = Öppna båda filerna
ContentBtnUpdatesOpenDevFile = Öppna Dev-fil
ContentBtnUpdatesOpenDiff = Öppna diff-fönster
ContentBtnUpdatesOpenProdFile = Öppna Prod-fil
ContentCbCopyLogInfoIncludeErrorLogs = Inkludera felloggar
ContentCbCopyLogInfoIncludeOutputFiles = Inkludera utdata-filer
ContentCbLogsFilterSuccessFailed = Misslyckade
ContentCbLogsFilterSuccessSuccess = Lyckade
ContentCbRollbackFilterTypePs1 = ps1
ContentCbRollbackFilterTypePs1Tooltip = Skriptfil
ContentCbRollbackFilterTypePsd1 = psd1
ContentCbRollbackFilterTypePsd1Tooltip = Data/Localization-fil
ContentCbRollbackFilterTypePsm1 = psm1
ContentCbRollbackFilterTypePsm1Tooltip = Modul-fil
ContentCbRollbackFilterTypeTxt = txt
ContentCbRollbackFilterTypeTxtTooltip = Dokumentations-/Informationsfil
ContentCbRollbackFilterTypeXaml = xaml
ContentCbRollbackFilterTypeXamlTooltip = GUI definitions fil
ContentCbShowDevFiles = Visa filer i dev
ContentChbPublishFiles = Publicera till prod
ContentDgDiffListColDevRow = Rad i dev-fil
ContentDgDiffListColLineNr = Radnummer
ContentDgDiffListColProdRow = Rad i prod-fil
ContentDgErrorLogsColLogDate = Loggningstid
ContentDgFailedUpdatesColInvalidLocalizations = Ogiltiga localizations
ContentDgFailedUpdatesColName = Uppdaterad fil
ContentDgFailedUpdatesColObsoleteFunctions = Föråldrade funktioner
ContentDgFailedUpdatesColOrphandLocalizations = Icke använda localizations
ContentDgFailedUpdatesColScriptInfo = Skriptinformation
ContentDgFailedUpdatesColTODOs = Kvarglömda TODO-anteckningar
ContentDgFailedUpdatesColUpdateAnyway = Uppdatera ändå
ContentDgFailedUpdatesColWritesToLog = Skriver log
ContentDgInvalidLocalizationsColLineNumber = Radnummer
ContentDgInvalidLocalizationsColScriptLine = Textrad
ContentDgInvalidLocalizationsColScriptVar = Variabel
ContentDgLogsColLogDate = Loggningstid
ContentDgLogsColOperator = Handläggare
ContentDgLogsColSuccess = Framgång
ContentDgObsoleteFunctionsColFunctionName = Funktionsnamn
ContentDgObsoleteFunctionsColHelpMessage = Information
ContentDgObsoleteFunctionsColLineNumbers = Radnummer
ContentDgOrphandLocalizationsColValue = Variabelvärde
ContentDgOrphandLocalizationsColVariable = Variabelnamn
ContentDgRollbacksColFileName = Filnamn
ContentDgRollbacksColType = Filtyp
ContentDgRollbacksColUpdated = Uppdaterad
ContentDgRollbacksColUpdatedBy = Uppdaterad av
ContentDgSIColHeaderInfoDesc = Beskrivning
ContentDgSIColHeaderTitle = Saknad information
ContentDgTDColHeaderTextL = Textrad
ContentDgTDColHeaderTextLN = Radnummer
ContentDgUpdatesColDevUpd = Uppdaterad i development
ContentDgUpdatesColName = Namn
ContentDgUpdatesColNew = Fil är ...
ContentDgUpdatesColProdState = Utvecklingsfas
ContentDgUpdatesColProdUpd = Uppdaterad i prod
ContentGbErrorLogsDisplayPeriod = Filtrera på period
ContentGbLogsDisplayPeriod = Filtrera på senast
ContentGbLogsFilter = Filtrera på lyckats
ContentGridFuncSynopsisInfo = Synopsis, eller kort beskrivning. Denna bör vara inte längre än en mening och ska överlag beskriva funktionens syfte.
ContentLblErrLogComputerName = Datornamn
ContentLblLogComputerNameTitle = Datornamn
ContentLblLogErrorLogTitle = Fellog
ContentLblLogOutputFileTitle = Fil för utdata
ContentLblLogTextTitle = Logtext
ContentLblLogUserInputTitle = Angiven input
ContentLblOperator = Handläggare
ContentLblRollbackFiltersTitle = Filteralternativ
ContentLblRollbackFilterTypeTitle = Visa enbart filtyp
ContentLblSeverity = Felkategori
ContentLblUserInput = Angiven input
ContentLlblErrorMessage = Felmeddelande
ContentRbErrorLogsDisplayPeriodAll = Allt
ContentRbErrorLogsDisplayPeriodRecent = Senaste veckan
ContentRbFuncNoteTypeInfo = Information
ContentRbFuncNoteTypeWarning = Varning
ContentRbLogsDisplayPeriodAll = Allt
ContentRbLogsDisplayPeriodRecent = Senaste veckan
ContentTblCodeTypeTitle = Välj typ av kodmall
ContentTblDevTitle = filer under utveckling
ContentTblExistingSubMenus = Existerande undermenyer
ContentTblExistingSubMenusTitle = Existerande undermenyer för vald objekttyp
ContentTblExpFuncHeader = Inställningar för funktion
ContentTblExpToolHeader = Inställningar för verktyg
ContentTblFuncAllowedUsersTitle = Användare med behörighet (ange sys-id)
ContentTblFuncAuthorTitle = Författare (om annan än du själv)
ContentTblFuncDescriptionTitle = Beskrivning
ContentTblFuncInputDataBoolTitle = Indata som sant eller falskt
ContentTblFuncInputDataListTitle = Indata med vallista
ContentTblFuncInputDataTitle = Indata
ContentTblFuncInvalidateDateTimeTitle = Sista tid som aktiv
ContentTblFuncMenuItemTitle = Menyrad
ContentTblFuncNameTitle = Funktionsnamn
ContentTblFuncNoRunspaceTitle = Använd inte separat runspace
ContentTblFuncNote = Anteckning
ContentTblFuncObjectClassTitle = Objektklass
ContentTblFuncOutputType = Typ av utdata
ContentTblFuncRequiredAdGroupsTitle = AD-grupper med behörighet
ContentTblFuncSearchedItemRequest = Sökt objekt önskas
ContentTblFuncStateTitle = Utvecklingsfas
ContentTblFuncSubMenuNewInfo = Välj en existerade undermeny, eller ange namnet på en ny
ContentTblFuncSubMenuTitle = Namn på undermeny
ContentTblFuncSynopsisTitle = Synopsis
ContentTblFuncValidStartDateTimeTitle = Blir aktiv
ContentTblInfo = Uppdatera enbart de filer du vet att du ändrat själv
ContentTblPHAllowedUsersTitle = Användare med behörighet (ange sys-id)
ContentTblPHAuthorTitle = Författare (om annan än du själv)
ContentTblPHCodeCommentTitle = Kommentar
ContentTblPHCodeTitle = PropHandler-kod
ContentTblPHDataSourceTitle = Datakälla
ContentTblPHDescriptionTitle = Beskrivning
ContentTblPHInvalidateDateTimeTitle = Sista tid som aktiv
ContentTblPHNameTitle = Attributnamn
ContentTblPHObjectClassTitle = Objektklass
ContentTblPHRequiredAdGroupsTitle = AD-grupper med behörighet
ContentTblPHStateTitle = Utvecklingsfas
ContentTblPHTitleTitle = Titel
ContentTblPHValidStartDateTimeTitle = Blir aktiv
ContentTblProdTitle = filer i produktion
ContentTblPropHandlerObjectClassTitle = Objektklass
ContentTblTestTitle = filer i testfas
ContentTblToolAllowedUsersTitle = Användare med behörighet (ange sys-id)
ContentTblToolAuthorTitle = Författare (om annan än du själv)
ContentTblToolDescriptionTitle = Beskrivning
ContentTblToolInvalidateDateTimeTitle = Sista tid som aktiv
ContentTblToolMenuItemTitle = Menyrad
ContentTblToolNameTitle = Verktygsnamn
ContentTblToolObjectOperationsTitle = Objekthantering
ContentTblToolRequiredAdGroupsTitle = AD-grupper med behörighet
ContentTblToolSeparateTitle = Separat
ContentTblToolStateTitle = Utvecklingsfas
ContentTblToolSubMenuNewInfo = Välj en existerade undermeny, eller ange namnet på en ny
ContentTblToolSubMenuTitle = Namn på undermeny
ContentTblToolSynopsisTitle = Synopsis
ContentTblToolValidStartDateTimeTitle = Blir aktiv
ContentTblUpdatedInProd = Dessa har uppdaterats i produktion, men inte i dev.
ContentTiCodeTypeFunction = Funktion
ContentTiCodeTypePropHandler = PropHandler
ContentTiCodeTypeTool = Verktyg
ContentTiErrorLogs = Felloggar
ContentTiFailedUpdates = Misslyckade uppdateringar
ContentTiKbSummary = KP-sammanfattning
ContentTiLogs = Loggar
ContentTiNewTemplate = Ny kodtemplate
ContentTiRollback = Rollbackmachine
ContentTiUpdated = Uppdaterade
ContentTiUpdatedInProd = Uppdaterade i prod
ContentTiUpdates = Uppdateringar
ContentTtGridFuncAllowedUsersInfo = En lista över användare som ska få speciell tillgång att använda funktionen. Dessa kommer få behörighet även om särskild AD-grupp anges för behörighet. Listan kan vara tillämplig ifall koden är i test-fas och utvalda personer behöver kontrollera funktionaliteten.
ContentTtGridFuncAuthorInfo = Vem ska anges som ansvarig författare/utvecklare. Detta anges om annan än du själv är ansvarig. Det ansvarige kommer då även att motta mail om felanmälan eller kommentar genom verktyget "Skicka felanmälan". Ange id i rutan.
ContentTtGridFuncDescriptionInfo = En någorlunda utförlig beskrivning över vad funktionen gör, ifall det behöver informeras hur den arbetar, och förslagsvis hur resultatet kommer se ut.
ContentTtGridFuncInputDataBoolInfo = Variabler som ska anges som sant eller falskt innan start av funktionen. Variabeln kan även anges som obligatorisk, och måste då anges innan funktionen kan startas. Värdet för varje given variabel kommer kopieras till funktionen som en boolean.
ContentTtGridFuncInputDataInfo = Variabler som ska anges innan start av funktionen. Variabeln kan även anges som obligatorisk, och måste då anges innan funktionen kan startas. Värdet för varje given variabel kommer kopieras till funktionen som en sträng.
ContentTtGridFuncInputDataListInfo = Variabler som ska anges utifrån en angiven lista innan start av funktionen. Variabeln kan även anges som obligatorisk, och måste då anges innan funktionen kan startas. Värdet för varje given variabel kommer kopieras till funktionen som en sträng.
ContentTtGridFuncInvalidateDateTimeInfo = Detta anger datum och tid då funktionen inte längre kan användas.
ContentTtGridFuncMenuItemInfo = Vilken text som ska visas i menyraden. Denna text får inte innehålla 'underscore' ('_') och bör vara tydlig med funktionens syfte.
ContentTtGridFuncNameInfo = Namn på funktionen. Namnet kan inte sättas i info-blocket i början av koden. Namnet måste ha ett godkänt verb som prefix.
ContentTtGridFuncNoRunspaceInfo = Om funktionen anges med NoRunspace kommer koden köras i samma process som huvudfönstret. Detta kan vara bra i vissa situationer när en separat process inte kan använda nödvändiga behörigheter eller process info. Att funktionen använder samma process innebär att fönstret kommer vara låst till dess att funktionen har kört färdigt.
ContentTtGridFuncNoteInfo = Ange information som kan vara behjälplig att visa innan funktionen startas. Texten kan anges som information eller varning.
ContentTtGridFuncObjectClassInfo = Välj vilken objekttyp som functionen ska arbeta mot/på. Menyraden kommer placeras i motsvarande meny specifik för objekttypen. Detta gör också att funktionen kommer få tillgång till sökt objekt om typen är samma. Om detta inte väljs, kommer funktionen placeras i modulen "OtherFunctions" och menyraden placeras då i menyn "Andra funktioner".
ContentTtGridFuncOutputTypeInfo = Definiera hur data ut från funktionen är formad eller hur den ska visas. 'String' - Data kommer vara format som en sträng och kommer visas som text utan speciell formatering. 'ObjectList' - Data kommer vara en lista av objekt. Objekten kommer listas med samtliga attribut i en tabell. 'List' - Data kommer vara en lista med strängar. 'None' - Data kommer inte returneras av funktionen.
ContentTtGridFuncRequiredAdGroupsInfo = En eller flera AD-grupper användare ska vara medlem i för att funktionen ska vara tillgängligt. Detta har inte prioritet över AllowedUsers. Om detta lämnas tomt, kommer alla ha behörighet.
ContentTtGridFuncSearchedItemRequestInfo = Ange vilket behov funktionen har av sökt objekt. 'None' - Inget behov och sökt objekt kommer inte kopieras till funktionen. 'Allowed' - Sökt objekt kan användas, men är inte nödvändigt. Om ett objekt har sökts och lästs in, kommer det kopieras till funktionen vid start. 'Required' - Sökt objekt behövs och menyraden kommer inte vara synlig om inget objekt har lästs in.
ContentTtGridFuncStateInfo = Vilken utvecklingsfas befinner sig koden i? Dev betyder att den är under utvecklingsfas och kommer enbart kunna köras i utvecklingsmiljön. Test och Prod kommer vara tillgängliga för publicering.
ContentTtGridFuncSubMenuInfo = Anger ifall menyraden ska placeras i en undermeny.
ContentTtGridFuncValidStartDateTimeInfo = Detta anger datum och tid då funktionen/verktyget kan börja användas.
ContentTtGridPHAllowedUsersInfo = En lista över användare som ska få speciell tillgång att använda verktyget. Dessa kommer få behörighet även om särskild AD-grupp anges för behörighet. Listan kan vara tillämplig ifall koden är i test-fas och utvalda personer behöver kontrollera funktionaliteten.
ContentTtGridPHAuthorInfo = Vem ska anges som ansvarig författare/utvecklare. Detta anges om annan än du själv är ansvarig. Det ansvarige kommer då även att motta mail om felanmälan eller kommentar genom verktyget "Skicka felanmälan". Ange id i rutan.
ContentTtGridPHCodeCommentInfo = En kort kommentar om vad PropHandlern är tänkt att göra. Denna kommer enbart placeras i modul-filen och är tänkt att vara beskrivande för andra att förstå vad koden ska göra.
ContentTtGridPHCodeInfo = Kod som ska köras i egenskap av PropHandler. För närmare information hur en PropHandler kodas, se wiki.
ContentTtGridPHDataSourceInfo = Vilken datakälla hämtas informationen i attributet från. 'Annan' (Other) betyder att informationen har hämtats, sammanställts av Fetchalon
ContentTtGridPHDescriptionInfo = En beskrivning av vad PropHandlern gör. Detta kommer visas i ToolTip för knappen som startar PropHandlern.
ContentTtGridPHInvalidateDateTimeInfo = Detta anger datum och tid då verktyget inte längre kan användas.
ContentTtGridPHNameInfo = Namn på det attribut som PropHandlern ska köras mot. Namnet måste vara korrekt stavat, annars kommer PropHandlern inte laddas. Ingen kontroll kommer göras här.
ContentTtGridPHObjectClassInfo = Välj vilken objekttyp som attributet ligger i, och då också PropHandlern ska arbeta mot/på.
ContentTtGridPHRequiredAdGroupsInfo = En eller flera AD-grupper användare ska vara medlem i för att verktyget ska vara tillgängligt. Detta har inte prioritet över AllowedUsers. Om detta lämnas tomt, kommer alla ha behörighet.
ContentTtGridPHStateInfo = Vilken utvecklingsfas befinner sig koden i? Dev betyder att den är under utvecklingsfas och kommer enbart kunna köras i utvecklingsmiljön. Test och Prod kommer vara tillgängliga för publicering.
ContentTtGridPHTitleInfo = Titel, eller kort beskrivning. Detta kommer visas som text i knappen för att köra PropHandler
ContentTtGridPHValidStartDateTimeInfo = Detta anger datum och tid då PropHandlern kan börja användas.
ContentTtGridPropHandlerObjectClassInfo = Välj vilken objektklass som attributet finns för. PropHandlern kommer enbart laddas för specifik kombination av datakälla, objekttyp och attributnamn.
ContentTtGridToolAllowedUsersInfo = En lista över användare som ska få speciell tillgång att använda verktyget. Dessa kommer få behörighet även om särskild AD-grupp anges för behörighet. Listan kan vara tillämplig ifall koden är i test-fas och utvalda personer behöver kontrollera funktionaliteten.
ContentTtGridToolAuthorInfo = Vem ska anges som ansvarig författare/utvecklare. Detta anges om annan än du själv är ansvarig. Det ansvarige kommer då även att motta mail om felanmälan eller kommentar genom verktyget "Skicka felanmälan". Ange id i rutan.
ContentTtGridToolDescriptionInfo = En någorlunda utförlig beskrivning över vad verktyget gör, ifall det behöver informeras hur den arbetar, och förslagsvis hur resultatet kommer se ut.
ContentTtGridToolInvalidateDateTimeInfo = Detta anger datum och tid då PropHandlern inte längre kan användas.
ContentTtGridToolMenuItemInfo = Vilken text som ska visas i menyraden. Denna text får inte innehålla 'underscore' ('_') och bör vara tydlig med verktygets syfte.
ContentTtGridToolNameInfo = Namn på verktyget. Namnet kan inte sättas i info-blocket i början av koden. Namnet måste ha ett godkänt verb som prefix. Namnet kommer även vara basnamnet på fil/-erna. 
ContentTtGridToolObjectOperationsInfo = Välj objekttyp som verktyget arbetar med. Menyraden kommer placeras i motsvarande meny specifik för objekttypen. Detta gör också att verktyget kommer få sökt objekt kopierat till sig när verktyget startaa. Om detta inte väljs, kommer menyraden placeras i menyn "Verktyg".
ContentTtGridToolRequiredAdGroupsInfo = En eller flera AD-grupper användare ska vara medlem i för att verktyget ska vara tillgängligt. Detta har inte prioritet över AllowedUsers. Om detta lämnas tomt, kommer alla ha behörighet.
ContentTtGridToolSeparateInfo = Ange om verktyget ska skapas som ett separat verktyg. Detta innebär att GUI måste hanteras av verktyget självt och kommer därför öppnas som ett eget fönster. När verktyget ska startas, kommer en separat process skapas upp, som verktyget arbetar i. Detta innebär även att ingen information kommer vara tillgänglig i huvudfönstret. När huvudfönstret stängs, görs försök att även verktygets fönster ska stängas.
ContentTtGridToolStateInfo = Vilken utvecklingsfas befinner sig koden i? Dev betyder att den är under utvecklingsfas och kommer enbart kunna köras i utvecklingsmiljön. Test och Prod kommer vara tillgängliga för publicering.
ContentTtGridToolSubMenuInfo = Anger ifall menyraden ska placeras i en undermeny.
ContentTtGridToolSynopsisInfo = Synopsis, eller kort beskrivning. Denna bör vara inte längre än en mening och ska överlag beskriva verktygets syfte.
ContentTtGridToolValidStartDateTimeInfo = Detta anger datum och tid då funktionen/verktyget kan börja användas.
ContentTtRbFuncNoteTypeInfo = Informationen kommer visas när funktionen startas från menyn. Om funktionen inte har någon input, men har information, kommer operationen pausas innan funktionen körs.
ContentTtRbFuncNoteTypeWarning = Anteckningen ska vara varning. Varningen kommer visas när funktionen startas från menyn. Om funktionen inte har någon input, men har en varning, kommer operationen pausas innan funktionen körs. Varningen måste bekräftas innan funktionen kan startas.
ContentTtTiCodeTypeFunction = Skapa en funktion som kommer vara tillgänglig i menyn till vänster i huvudfönstret
ContentTtTiCodeTypePropHandler = Skapa en PropHandler som kan köra för ett attribut hos sökt objekt, förutsatt att attributet är satt att visas i standardvyn
ContentTtTiCodeTypeTool = Skapa ett verktyg som kommer visas med sitt egna GUI inuti huvudfönstret
CvsFuncObjectClassList = Mapp,DirectoryInfo;Fil,FileInfo;Användare,User;Grupp,Group;Dator,Computer;Skrivare,Printqueue;<Välj objektklass>,null
CvsPropHandlerObjectClassList = Mapp,DirectoryInfo;Fil,FileInfo;Användare,User;Grupp,Group;Dator,Computer;Skrivare,Printqueue;< Välj objektklass >,null
CvsPsVerbs = <Välj verb>
CvsToolObjectOperationsList = Mapp,DirectoryInfo;Fil,FileInfo;Användare,User;Grupp,Group;Dator,Computer;Skrivare,Printqueue;< Välj objekttyp >,null
ErrNewCodeTemplateAllowedUsersNotFound = En eller flera id:n hittades inte
ErrNewCodeTemplateAuthorNotFound = Hittar ingen användare med angivet namn
ErrNewCodeTemplateBadInvalidateDate = Giltig datumsträng för slut
ErrNewCodeTemplateBadValidDate = Giltig datumsträng för start
ErrNewCodeTemplateDefaultValNotInOptionsList = Detta värde finns inte med i listan
ErrNewCodeTemplateDescriptionEmpty = Beskrivning måste anges
ErrNewCodeTemplateEndBeforeNow = Slutdatum har redan varit
ErrNewCodeTemplateEndBeforeStart = Slutdatum kan inte vara före startdatum
ErrNewCodeTemplateEndParseError = Kan inte konvertera texten till giltigt datum/tid. Korrekt format är 'ÅÅÅ-MM-DD tt:mm:ss'
ErrNewCodeTemplateInputNameExists = Namnet har redan angivits för en annan indata variabel
ErrNewCodeTemplateInputNameInvalidCharacter = Namnet får endast innehålla bokstäver
ErrNewCodeTemplateMenuItemEmpty = Menyrad måste anges
ErrNewCodeTemplateMenuItemExists = Angiven text används för en annan funktion/verktyg, vilket kan bli förvirrande.
ErrNewCodeTemplateMenuItemInvalidCharacters = Texten innehåller otillåtna tecken. Texten får bara innehålla bokstäver och siffror, utan underscore
ErrNewCodeTemplateMenuItemUnderscore = Texten innehåller '_' vilket kan ställa till det med kortkommandon
ErrNewCodeTemplateMissingCodeType = Ingen kodmall vald
ErrNewCodeTemplateMissingDescription = Beskrivning
ErrNewCodeTemplateMissingFuncObjectClass = Objektklass funktionen ska arbeta mot
ErrNewCodeTemplateMissingFuncOutputType = Typ av utdata
ErrNewCodeTemplateMissingFuncSearchedItemRequest = Behov av sökt objekt
ErrNewCodeTemplateMissingInfo = Kan inte fortsätta då följande nödvändig information saknas
ErrNewCodeTemplateMissingInputDataBoolVarNoDesc = En eller flera indata som sant eller falskt saknar beskrivning
ErrNewCodeTemplateMissingInputDataListVarNoDesc = En eller flera indata med vallista saknar beskrivning
ErrNewCodeTemplateMissingInputDataListVarNoList = En eller flera indata med vallista saknar vallist
ErrNewCodeTemplateMissingInputDataVarNoDesc = En eller flera indata saknar beskrivning
ErrNewCodeTemplateMissingMenuItem = Menyrad
ErrNewCodeTemplateMissingName = Namn
ErrNewCodeTemplateMissingNameVerb = Verb prefix
ErrNewCodeTemplateMissingState = Utvecklingsfas
ErrNewCodeTemplateMissingSynopsis = Synopsis
ErrNewCodeTemplateNoIdentifyableId = Inte ett identifierbart id
ErrNewCodeTemplatePHTitleEmpty = Titel måste anges
ErrNewCodeTemplateRequiredAdGroupsNotFound = En eller flera namn hittades inte
ErrNewCodeTemplateStartAfterEnd = Startdatum kan inte vara efter slutdatum
ErrNewCodeTemplateStartEndSame = Start- och slutdatum kan inte vara samma
ErrNewCodeTemplateStartMalformed = Texten följer inte formatet 'ÅÅÅÅ-MM-DD' eller 'ÅÅÅÅ-MM-DD tt:mm:ss' och kan därför inte användas
ErrNewCodeTemplateStartParseError = Kan inte konvertera texten till giltigt datum/tid. Korrekt format är 'ÅÅÅÅ-MM-DD tt:mm:ss'
ErrNewCodeTemplateStateMissing = Utvecklingsfas måste vara angiven
ErrNewCodeTemplateSubMenuInvalidCharacters = Texten för undermeny får enbart innehålla bokstäver
ErrNewCodeTemplateSynopsisEmpty = Synopsis måste anges
ErrNewCodeTemplateSynopsisUnderscore = Texten innehåller '_' vilket kan ställa till det med kortkommandon
ErrNewCommandIllegalCharacters = Namnet innehåller icke tillåtna tecken
ErrNewCommandNameExists = Det angivna namnet finns redan
ErrNewFuncNoNameInput = Ett namn måste anges
ErrNewFuncNoteTextNotSet = Text måste anges
ErrNewFuncNoteTypeNotSet = Note-typ måste anges
ErrNewFuncObjectClassNotGiven = Objektklass måste anges
ErrNewFuncTemplateDescriptionNotGiven = Beskrivning måste anges
ErrNewFuncTemplateVerbNotGiven = Ett verb måste anges
ErrNewPHDataSourceNotGiven = Datakälla måsta anges
ErrNewPHDescriptionNotGiven = Beskrivning måste anges
ErrNewPHMoreDescriptiveCodeComment = Vänligen ange en något mer beskrivande kommentar
ErrNewPHNameUsed = Det angivna attributet har redan en PropHandler
ErrNewPHNoCodeComment = En kommentar bör anges för att underlätta läsningen av modul-filen
ErrNewPHNoNameInput = Ett attributnamn måste anges
ErrNewPHObjectClassNotGiven = Objektklass måste anges
ErrNewToolNoNameInput = Ett namn måste anges
ErrNewToolObjectOperationsNotGiven = Objekttyp måste anges
ErrNewToolTemplateDescriptionNotGiven = Beskrivning måste anges
ErrNewToolTemplateVerbNotGiven = Ett verb måste anges
ErrWritingNewPH = Fel uppstod när filen skulle skrivas
LogFailedUpdates = skript misslyckades att uppdateras
LogFailedUpdatesName = Skriptnamn
LogFailedUpdatesTestResults = Testresultat:
LogOpenDiffWindow = Kontrollerar diff
LogUpdatedIntro = Uppdaterat
StrAdmPrefix = sys
StrCheckingUpdatesCheckFiles = Kontrollerar uppdateringar
StrCheckingUpdatesGetFiles = Hämtar filer
StrDiffRowAdded = < Rad tillagd >
StrDiffRowRemoved = < Rad borttagen >
StrErrorlogsNotLoaded = Felloggar har inte lästs in
StrFailedTestCount = Antal test som felade
StrFunctionCreated = Funktion har nu skapats och placerats i modul-filen. Vill du öppna filen?
StrFunctionState = Tillhörande funktion i
StrIcInputDataBoolDescriptionTitle = Beskrivning
StrIcInputDataBoolMandatoryTitle = Obligatorisk
StrIcInputDataBoolNameTitle = Variabelnamn
StrIcInputDataDescriptionTitle = Beskrivning
StrIcInputDataListDefaultValueTitle = Standardvärde
StrIcInputDataListDescriptionTitle = Beskrivning
StrIcInputDataListMandatoryTitle = Obligatorisk
StrIcInputDataListNameTitle = Variabelnamn
StrIcInputDataListOptionslistTitle = Värdelista
StrIcInputDataMandatoryTitle = Obligatorisk
StrIcInputDataNameTitle = Variabelnamn
StrInsertPHCodeHere = < Här placeras koden för PropHandlern >
StrKbSummaryAcceptsSI = (Accepterar sökt objekt)
StrKbSummaryAvailableForBoTitle = Tillgängliga för BO
StrKbSummaryCopied = Sammanfattning har kopierats till clipboard
StrKbSummaryNeedsSI = (Kräver sökt objekt)
StrKbSummaryPreamble = <h3>Listförklaring</h3><p>I listan visas namnet (detta är den text som visas i menyerna), samt en förklaring för vad funktionen/verktyget gör.</p><p>&nbsp;</p><h3>Förklaring olika textstilar</h3><p><em>Kursiv - Detta är ett verktyg där all GUI visas i huvudfönstret</em></p><p><strong>Fet - Detta är ett verktyg som öppnas i ett eget, separat fönster</strong></p><p><span style="text-decoration: underline;">Understruken - Detta öpnnar en länk i Chrome, eller öppnar/startar annan applikation, de flesta ger ingen output</span></p><p>&nbsp;</p><h3>Input för funktioner</h3><p>Hur input ska anges för funktioner ska informeras när funktionen initieras, antingen som ett värde, eller som flera. Detta står ovanför textrutan för input-värdet.</p><p>Ifall värdet är nödvändigt för funktionen, kommer det visas en röd stjärna. Det görs ingen kontroll av värdet, så som stavning eller att t.ex. en dator har det namnet, innan funktionen körs. Detta tas om hand av funktionen.</p><p>&nbsp;</p><h4>Kräver sökt objekt</h4><ul style="list-style-position: inside;"><li>Funktionen är markerad med grönt framför texten på menyraden</li><li><strong>Kräver</strong> att objekt har sökts och laddats in, annars kommer menyraden inte visas</li><li>Funktionen kräver enbart objektet som input och kommer starta på en gång</li></ul><h4>Accepterar sökt objekt</h4><ul style="list-style-position: inside;"><li>Funktionen är markerad med gult framför texten på menyraden</li><li>Funktionen kan arbetat med sökt objekt och tar dess namn som input</li><li>Sökt objekts namn kommer läggas in i första textrutan</li></ul><p>&nbsp;</p>
StrKbSummarySubCategoryTitlePrefix = Undermeny
StrKdSummaryCommands = Funktioner / verktyg
StrKdSummaryDescription = Beskrivning av funktion/verktyg
StrKdSummaryMenuItem = Menyrad
StrLogInfoCopyComputerName = Datornamn
StrLogInfoCopyDate = Datum
StrLogInfoCopyError = Fel
StrLogInfoCopyErrorFilePath = Sökväg till fil
StrLogInfoCopyLogText = Loggtext
StrLogInfoCopyOperator = Handläggare
StrLogInfoCopyOutputFile = Utdata
StrLogInfoCopyOutputFilePath = Sökväg till fil
StrLogInfoCopySuccess = Lyckades
StrLogInfoCopyTitle = Logg-info för skript
StrLogSearchNoType = Ingen typ vald
StrNewFileTitle = < Ny fil >
StrNewFuncObjectOperationsNoneChosen = Funktionen kommer finnas under menyn "Andra funktioner"
StrNewFuncObjectOperationsTypeChosen = Funktionen kommer finnas under menyn
StrNewToolObjectOperationsNoneChosen = Verktyget kommer placeras under menyn "Verktyg"
StrNewToolObjectOperationsTypeChosen = Verktyget kommer placeras under menyn
StrNoFailedSelected = Inga filer markerade för uppdatering
StrNoScriptfile = Ingen skriptfil som innehåller information hittades
StrNotAllowedAnyway = Skript kan inte uppdateras då det bryter mot nödvändiga regler
StrNoUpdaterSpecified = <Ej angiven>
StrNoUpdates = Inga uppdaterade filer
StrRollbackDone = Fil tillbakarullad
StrRollbackInfoCopyFileLogs = Filversioner
StrRollbackInfoCopyTitle = Uppdateringshistorik för
StrRollbackInfoCopyUpdated = Datum
StrRollbackInfoCopyUpdater = Uppdaterad av
StrRollbackName = uppdaterad
StrRollbackPathNotFound = Filen hittas inte i produktion. Denna fil har troligen ersatts av annan fil, eller döpts om. Filen bör därför inte rullas tillbaka.
StrRollbackVerification = Vill du ersätta filen i produktion med denna fil?
StrRollbackVerificationDate = Filversion att rulla tillbaka:
StrRollbackVerificationPath = Fil att ersätta:
StrScriptState = Tillhörande skript i
StrSelectPropHandlerDataSource = < Välj datakälla >
StrSelectState = < Välj utvecklingsfas >
StrSeparateToolCreated = Skriptfil har nu skapats. Vill du öppna filen?
StrUpdatedFileIsNew = Ny
StrUpdatedFileIsUpdated = Uppdaterad
StrUpdates = uppdaterade filer
StrUpdatesInProd = filer har ändrats i produktion, men inte i dev
'@
