ConvertFrom-StringData @'
CodeRegKbSummaryReqAdGrps = (Rol_SD_Backoffice)|(Rol_SD_OpRes)
ContentBtnCheckForUpdates = Sök efter uppdateringar
ContentBtnClearErrorLogSearch = Avbryt sök
ContentBtnClearLogSearch = Avbryt sök
ContentBtnCopyErrorInfo = Kopiera information
ContentBtnCopyLogInfo = Kopiera
ContentBtnCopyRollbackInfo = Kopiera lista
ContentBtnCreateKdSummary = Skapa sammanfattning till KB
ContentBtnDiffCancel = Avbryt
ContentBtnDoRollback = Rulla tillbaka filversion
ContentBtnErrorLogSearch = Sök
ContentBtnListRollbacks = Lista rollbacks
ContentBtnLogSearch = Sök
ContentBtnOpenErrorLog = Öppna fellogg
ContentBtnOpenFailed = Öppna
ContentBtnOpenOutputFile = Öppna fil
ContentBtnOpenPopupCopyLogInfo = Kopiera info
ContentBtnOpenRollbackFile = Öppna fil
ContentBtnReadErrorLogs = Läs in felloggar
ContentBtnReadErrorLogsAgain = Läs in felloggar (igen)
ContentBtnReadLogs = Läs in loggar
ContentBtnReadLogsAgain = Läs in loggar (igen)
ContentBtnUpdatedInProdOpenBothFiles = Öppna båda filerna
ContentBtnUpdatedInProdOpenDevFile = Öppna Dev-fil
ContentBtnUpdatedInProdOpenDiffs = Öppna diff-fönster
ContentBtnUpdatedInProdOpenProdFile = Öppna Prod-fil
ContentBtnUpdateFailedScripts = Uppdatera checkade filer
ContentBtnUpdateScripts = Uppdatera markerade filer
ContentBtnUpdatesOpenBothFiles = Öppna båda filerna
ContentBtnUpdatesOpenDevFile = Öppna Dev-fil
ContentBtnUpdatesOpenDiff = Öppna diff-fönster
ContentBtnUpdatesOpenProdFile = Öppna Prod-fil
ContentCbCopyLogInfoIncludeErrorLogs = Inkludera felloggar
ContentCbCopyLogInfoIncludeOutputFiles = Inkludera utdata-filer
ContentCbLogsFilterSuccessFailed = Misslyckade
ContentCbLogsFilterSuccessSuccess = Lyckade
ContentCbRollbackFilterTypePs1 = ps1
ContentCbRollbackFilterTypePs1Tooltip = Skriptfil
ContentCbRollbackFilterTypePsd1 = psd1
ContentCbRollbackFilterTypePsd1Tooltip = Data/Localization-fil
ContentCbRollbackFilterTypePsm1 = psm1
ContentCbRollbackFilterTypePsm1Tooltip = Modul-fil
ContentCbRollbackFilterTypeTxt = txt
ContentCbRollbackFilterTypeTxtTooltip = Dokumentations-/Informationsfil
ContentCbRollbackFilterTypeXaml = xaml
ContentCbRollbackFilterTypeXamlTooltip = GUI definitions fil
ContentCbShowDevFiles = Visa filer i dev
ContentChbPublishFiles = Publicera till prod
ContentDgDiffListColDevRow = Rad i dev-fil
ContentDgDiffListColLineNr = Radnummer
ContentDgDiffListColProdRow = Rad i prod-fil
ContentDgErrorLogsColLogDate = Loggningstid
ContentDgFailedUpdatesColInvalidLocalizations = Ogiltiga localizations
ContentDgFailedUpdatesColName = Uppdaterad fil
ContentDgFailedUpdatesColObsoleteFunctions = Föråldrade funktioner
ContentDgFailedUpdatesColOrphandLocalizations = Icke använda localizations
ContentDgFailedUpdatesColScriptInfo = Skriptinformation
ContentDgFailedUpdatesColTODOs = Kvarglömda TODO-anteckningar
ContentDgFailedUpdatesColUpdateAnyway = Uppdatera ändå
ContentDgFailedUpdatesColWritesToLog = Skriver log
ContentDgInvalidLocalizationsColLineNumber = Radnummer
ContentDgInvalidLocalizationsColScriptLine = Textrad
ContentDgInvalidLocalizationsColScriptVar = Variabel
ContentDgLogsColLogDate = Loggningstid
ContentDgLogsColOperator = Handläggare
ContentDgLogsColSuccess = Framgång
ContentDgObsoleteFunctionsColFunctionName = Funktionsnamn
ContentDgObsoleteFunctionsColHelpMessage = Information
ContentDgObsoleteFunctionsColLineNumbers = Radnummer
ContentDgOrphandLocalizationsColValue = Variabelvärde
ContentDgOrphandLocalizationsColVariable = Variabelnamn
ContentDgRollbacksColFileName = Filnamn
ContentDgRollbacksColType = Filtyp
ContentDgRollbacksColUpdated = Uppdaterad
ContentDgRollbacksColUpdatedBy = Uppdaterad av
ContentDgSIColHeaderInfoDesc = Beskrivning
ContentDgSIColHeaderTitle = Saknad information
ContentDgTDColHeaderTextL = Textrad
ContentDgTDColHeaderTextLN = Radnummer
ContentDgUpdatesColDevUpd = Uppdaterad i development
ContentDgUpdatesColName = Namn
ContentDgUpdatesColNew = Fil är ...
ContentDgUpdatesColProdState = Utvecklingsfas
ContentDgUpdatesColProdUpd = Uppdaterad i prod
ContentGbErrorLogsDisplayPeriod = Filtrera på period
ContentGbLogsDisplayPeriod = Filtrera på senast
ContentGbLogsFilter = Filtrera på lyckats
ContentLblErrLogComputerName = Datornamn
ContentLblLogComputerNameTitle = Datornamn
ContentLblLogErrorLogTitle = Fellog
ContentLblLogOutputFileTitle = Fil för utdata
ContentLblLogTextTitle = Logtext
ContentLblLogUserInputTitle = Angiven input
ContentLblOperator = Handläggare
ContentLblRollbackFiltersTitle = Filteralternativ
ContentLblRollbackFilterTypeTitle = Visa enbart filtyp
ContentLblSeverity = Felkategori
ContentLblUserInput = Angiven input
ContentLlblErrorMessage = Felmeddelande
ContentRbErrorLogsDisplayPeriodAll = Allt
ContentRbErrorLogsDisplayPeriodRecent = Senaste veckan
ContentRbLogsDisplayPeriodAll = Allt
ContentRbLogsDisplayPeriodRecent = Senaste veckan
ContentTblDevTitle = filer under utveckling
ContentTblInfo = Uppdatera enbart de filer du vet att du ändrat själv
ContentTblProdTitle = filer i produktion
ContentTblTestTitle = filer i testfas
ContentTblUpdatedInProd = Dessa har uppdaterats i produktion, men inte i dev.
ContentTiErrorLogs = Felloggar
ContentTiFailedUpdates = Misslyckade uppdateringar
ContentTiKbSummary = KB-sammanfattning
ContentTiLogs = Loggar
ContentTiRollback = Rollbackmachine
ContentTiUpdated = Uppdaterade
ContentTiUpdatedInProd = Uppdaterade i prod
ContentTiUpdates = Uppdateringar
LogFailedUpdates = skript misslyckades att uppdateras
LogFailedUpdatesName = Skriptnamn
LogFailedUpdatesTestResults = Testresultat:
LogOpenDiffWindow = Kontrollerar diff
LogUpdatedIntro = Uppdaterat
StrCheckingUpdatesCheckFiles = Kontrollerar uppdateringar
StrCheckingUpdatesGetFiles = Hämtar filer
StrDiffRowAdded = < Rad tillagd >
StrDiffRowRemoved = < Rad borttagen >
StrErrorlogsNotLoaded = Felloggar har inte lästs in
StrFailedTestCount = Antal test som felade
StrFunctionState = Tillhörande funktion i
StrKbSummaryAcceptsSI = (Accepterar sökt objekt)
StrKbSummaryAvailableForBoTitle = Tillgängliga för BO
StrKbSummaryCopied = Sammanfattning har kopierats till clipboard
StrKbSummaryNeedsSI = (Kräver sökt objekt)
StrKbSummaryPreamble = <h3>Listförklaring</h3><p>I listan visas namnet (detta är den text som visas i menyerna), samt en förklaring för vad funktionen/verktyget gör.</p><p>&nbsp;</p><h3>Förklaring olika textstilar</h3><p><em>Kursiv - Detta är ett verktyg där all GUI visas i huvudfönstret</em></p><p><strong>Fet - Detta är ett verktyg som öppnas i ett eget, separat fönster</strong></p><p><span style="text-decoration: underline;">Understruken - Detta öpnnar en länk i Chrome, eller öppnar/startar annan applikation, de flesta ger ingen output</span></p><p>&nbsp;</p><h3>Input för funktioner</h3><p>Hur input ska anges för funktioner ska informeras när funktionen initieras, antingen som ett värde, eller som flera. Detta står ovanför textrutan för input-värdet.</p><p>Ifall värdet är nödvändigt för funktionen, kommer det visas en röd stjärna. Det görs ingen kontroll av värdet, så som stavning eller att t.ex. en dator har det namnet, innan funktionen körs. Detta tas om hand av funktionen.</p><p>&nbsp;</p><h4>Kräver sökt objekt</h4><ul style="list-style-position: inside;"><li>Funktionen är markerad med grönt framför texten på menyraden</li><li><strong>Kräver</strong> att objekt har sökts och laddats in, annars kommer menyraden inte visas</li><li>Funktionen kräver enbart objektet som input och kommer starta på en gång</li></ul><h4>Accepterar sökt objekt</h4><ul style="list-style-position: inside;"><li>Funktionen är markerad med gult framför texten på menyraden</li><li>Funktionen kan arbetat med sökt objekt och tar dess namn som input</li><li>Sökt objekts namn kommer läggas in i första textrutan</li></ul><p>&nbsp;</p>
StrKbSummarySubCategoryTitlePrefix = Undermeny
StrLogInfoCopyComputerName = Datornamn
StrLogInfoCopyDate = Datum
StrLogInfoCopyError = Fel
StrLogInfoCopyErrorFilePath = Sökväg till fil
StrLogInfoCopyLogText = Loggtext
StrLogInfoCopyOperator = Handläggare
StrLogInfoCopyOutputFile = Utdata
StrLogInfoCopyOutputFilePath = Sökväg till fil
StrLogInfoCopySuccess = Lyckades
StrLogInfoCopyTitle = Logg-info för skript
StrLogSearchNoType = Ingen typ vald
StrNewFileTitle = < Ny fil >
StrNoFailedSelected = Inga filer markerade för uppdatering
StrNoScriptfile = Ingen skriptfil som innehåller information hittades
StrNotAllowedAnyway = Skript kan inte uppdateras då det bryter mot nödvändiga regler
StrNoUpdaterSpecified = <Ej angiven>
StrNoUpdates = Inga uppdaterade filer
StrRollbackDone = Fil tillbakarullad
StrRollbackInfoCopyFileLogs = Filversioner
StrRollbackInfoCopyTitle = Uppdateringshistorik för
StrRollbackInfoCopyUpdated = Datum
StrRollbackInfoCopyUpdater = Uppdaterad av
StrRollbackName = uppdaterad
StrRollbackPathNotFound = Filen hittas inte i produktion. Denna fil har troligen ersatts av annan fil, eller döpts om. Filen bör därför inte rullas tillbaka.
StrRollbackVerification = Vill du ersätta filen i produktion med denna fil?
StrRollbackVerificationDate = Filversion att rulla tillbaka:
StrRollbackVerificationPath = Fil att ersätta:
StrScriptState = Tillhörande skript i
StrUpdatedFileIsNew = Ny
StrUpdatedFileIsUpdated = Uppdaterad
StrUpdates = uppdaterade filer
StrUpdatesInProd = filer har ändrats i produktion, men inte i dev
'@
