ConvertFrom-StringData @'
CodeRegKbSummaryReqAdGrps = (Rol_SD_Backoffice)|(Rol_SD_OpRes)
ContentBtnAddInputVariable = Ny variabel
ContentBtnAddInputVariableBool = Ny variabel
ContentBtnAddInputVariableList = Ny variabel lista
ContentBtnAddSettingTitle = Lägg till inställning
ContentBtnCheckForUpdates = Sök efter uppdateringar
ContentBtnClearErrorLogSearch = Avbryt sök
ContentBtnClearLogSearch = Avbryt sök
ContentBtnCopyErrorInfo = Kopiera information
ContentBtnCopyLogInfo = Kopiera
ContentBtnCopyRollbackInfo = Kopiera lista
ContentBtnCreateCodeTemplate = Skapa kodmall
ContentBtnCreateKdSummary = Skapa sammanfattning till KB
ContentBtnDiffCancel = Avbryt
ContentBtnDoRollback = Rulla tillbaka filversion
ContentBtnErrorLogSearch = Sök
ContentBtnListRollbacks = Lista rollbacks
ContentBtnLogSearch = Sök
ContentBtnOpenErrorLog = Öppna fellogg
ContentBtnOpenFailed = Öppna
ContentBtnOpenOutputFile = Öppna fil
ContentBtnOpenPopupCopyLogInfo = Kopiera info
ContentBtnOpenRollbackFile = Öppna fil
ContentBtnReadErrorLogs = Läs in felloggar
ContentBtnReadErrorLogsAgain = Läs in felloggar (igen)
ContentBtnReadLogs = Läs in loggar
ContentBtnReadLogsAgain = Läs in loggar (igen)
ContentBtnResetTemplateInfo = Återställ
ContentBtnUpdatedInProdOpenBothFiles = Öppna båda filerna
ContentBtnUpdatedInProdOpenDevFile = Öppna Dev-fil
ContentBtnUpdatedInProdOpenDiffs = Öppna diff-fönster
ContentBtnUpdatedInProdOpenProdFile = Öppna Prod-fil
ContentBtnUpdateFailedScripts = Uppdatera checkade filer
ContentBtnUpdateScripts = Uppdatera markerade filer
ContentBtnUpdatesOpenBothFiles = Öppna båda filerna
ContentBtnUpdatesOpenDevFile = Öppna Dev-fil
ContentBtnUpdatesOpenDiff = Öppna diff-fönster
ContentBtnUpdatesOpenProdFile = Öppna Prod-fil
ContentCbCopyLogInfoIncludeErrorLogs = Inkludera felloggar
ContentCbCopyLogInfoIncludeOutputFiles = Inkludera utdata-filer
ContentCbLogsFilterSuccessFailed = Misslyckade
ContentCbLogsFilterSuccessSuccess = Lyckade
ContentCbRollbackFilterTypePs1 = ps1
ContentCbRollbackFilterTypePs1Tooltip = Skriptfil
ContentCbRollbackFilterTypePsd1 = psd1
ContentCbRollbackFilterTypePsd1Tooltip = Data/Localization-fil
ContentCbRollbackFilterTypePsm1 = psm1
ContentCbRollbackFilterTypePsm1Tooltip = Modul-fil
ContentCbRollbackFilterTypeTxt = txt
ContentCbRollbackFilterTypeTxtTooltip = Dokumentations-/Informationsfil
ContentCbRollbackFilterTypeXaml = xaml
ContentCbRollbackFilterTypeXamlTooltip = GUI definitions fil
ContentCbShowDevFiles = Visa filer i dev
ContentChbPublishFiles = Publicera till prod
ContentDgDiffListColDevRow = Rad i dev-fil
ContentDgDiffListColLineNr = Radnummer
ContentDgDiffListColProdRow = Rad i prod-fil
ContentDgErrorLogsColLogDate = Loggningstid
ContentDgFailedUpdatesColInvalidLocalizations = Ogiltiga localizations
ContentDgFailedUpdatesColName = Uppdaterad fil
ContentDgFailedUpdatesColObsoleteFunctions = Föråldrade funktioner
ContentDgFailedUpdatesColOrphandLocalizations = Icke använda localizations
ContentDgFailedUpdatesColScriptInfo = Skriptinformation
ContentDgFailedUpdatesColTODOs = Kvarglömda TODO-anteckningar
ContentDgFailedUpdatesColUpdateAnyway = Uppdatera ändå
ContentDgFailedUpdatesColWritesToLog = Skriver log
ContentDgInvalidLocalizationsColLineNumber = Radnummer
ContentDgInvalidLocalizationsColScriptLine = Textrad
ContentDgInvalidLocalizationsColScriptVar = Variabel
ContentDgLogsColLogDate = Loggningstid
ContentDgLogsColOperator = Handläggare
ContentDgLogsColSuccess = Framgång
ContentDgObsoleteFunctionsColFunctionName = Funktionsnamn
ContentDgObsoleteFunctionsColHelpMessage = Information
ContentDgObsoleteFunctionsColLineNumbers = Radnummer
ContentDgOrphandLocalizationsColValue = Variabelvärde
ContentDgOrphandLocalizationsColVariable = Variabelnamn
ContentDgRollbacksColFileName = Filnamn
ContentDgRollbacksColType = Filtyp
ContentDgRollbacksColUpdated = Uppdaterad
ContentDgRollbacksColUpdatedBy = Uppdaterad av
ContentDgSIColHeaderInfoDesc = Beskrivning
ContentDgSIColHeaderTitle = Saknad information
ContentDgTDColHeaderTextL = Textrad
ContentDgTDColHeaderTextLN = Radnummer
ContentDgUpdatesColDevUpd = Uppdaterad i development
ContentDgUpdatesColName = Namn
ContentDgUpdatesColNew = Fil är ...
ContentDgUpdatesColProdState = Utvecklingsfas
ContentDgUpdatesColProdUpd = Uppdaterad i prod
ContentGbErrorLogsDisplayPeriod = Filtrera på period
ContentGbLogsDisplayPeriod = Filtrera på senast
ContentGbLogsFilter = Filtrera på lyckats
ContentLblErrLogComputerName = Datornamn
ContentLblLogComputerNameTitle = Datornamn
ContentLblLogErrorLogTitle = Fellog
ContentLblLogOutputFileTitle = Fil för utdata
ContentLblLogTextTitle = Logtext
ContentLblLogUserInputTitle = Angiven input
ContentLblOperator = Handläggare
ContentLblRollbackFiltersTitle = Filteralternativ
ContentLblRollbackFilterTypeTitle = Visa enbart filtyp
ContentLblSeverity = Felkategori
ContentLblUserInput = Angiven input
ContentLlblErrorMessage = Felmeddelande
ContentRbCodeTypeFunction = Funktion
ContentRbCodeTypeTool = Verktyg
ContentRbErrorLogsDisplayPeriodAll = Allt
ContentRbErrorLogsDisplayPeriodRecent = Senaste veckan
ContentRbFuncNoteTypeInfo = Information
ContentRbFuncNoteTypeWarning = Varning
ContentRbLogsDisplayPeriodAll = Allt
ContentRbLogsDisplayPeriodRecent = Senaste veckan
ContentTblAllowedUsersTitle = Användare med behörighet (ange sys-id)
ContentTblAuthorTitle = Författare (om annan än du själv)
ContentTblCodeTypeTitle = Välj typ av kodmall
ContentTblDescriptionTitle = Beskrivning
ContentTblDevTitle = filer under utveckling
ContentTblExistingSubMenus = Existerande undermenyer
ContentTblExistingSubMenusTitle = Existerande undermenyer för vald objekttyp
ContentTblExpFuncHeader = Inställningar för funktion
ContentTblExpToolHeader = Inställningar för verktyg
ContentTblFuncNoRunspaceTitle = Använd inte separat runspace
ContentTblFuncNote = Anteckning
ContentTblFuncObjectClassTitle = Objektklass
ContentTblFuncOutputType = Typ av utdata
ContentTblFuncSearchedItemRequest = Sökt objekt önskas
ContentTblInfo = Uppdatera enbart de filer du vet att du ändrat själv
ContentTblInputDataBoolTitle = Indata som sant eller falskt
ContentTblInputDataListTitle = Indata med vallista
ContentTblInputDataTitle = Indata
ContentTblInvalidateDateTimeTitle = Sista tid som aktiv
ContentTblMenuItemTitle = Menyrad
ContentTblNameTitle = Namn
ContentTblProdTitle = filer i produktion
ContentTblRequiredAdGroupsTitle = AD-grupper med behörighet
ContentTblStateTitle = Utvecklingsfas
ContentTblSubMenuNewInfo = Välj en existerade undermeny, eller ange namnet på en ny
ContentTblSubMenuTitle = Namn på undermeny
ContentTblSynopsisTitle = Synopsis
ContentTblTestTitle = filer i testfas
ContentTblToolObjectOperationsTitle = Objekthantering
ContentTblToolSeparateTitle = Separat
ContentTblUpdatedInProd = Dessa har uppdaterats i produktion, men inte i dev.
ContentTblValidStartDateTimeTitle = Blir aktiv
ContentTiErrorLogs = Felloggar
ContentTiFailedUpdates = Misslyckade uppdateringar
ContentTiKbSummary = KP-sammanfattning
ContentTiLogs = Loggar
ContentTiNewTemplate = Ny funktion/verktyg
ContentTiRollback = Rollbackmachine
ContentTiUpdated = Uppdaterade
ContentTiUpdatedInProd = Uppdaterade i prod
ContentTiUpdates = Uppdateringar
ContentTtGridAllowedUsersInfo = En lista över användare som ska få speciell tillgång att använda funktionen/verktyget. Dessa kommer få behörighet även om särskild AD-grupp anges för behörighet. Listan kan vara tillämplig ifall koden är i test-fas och utvalda personer behöver kontrollera funktionaliteten.
ContentTtGridAuthorInfo = Vem ska anges som ansvarig författare/utvecklare. Detta anges om annan än du själv är ansvarig. Det ansvarige kommer då även att motta mail om felanmälan eller kommentar genom verktyget "Skicka felanmälan". Ange id i rutan.
ContentTtGridDescriptionInfo = En någorlunda utförlig beskrivning över vad funktionen/verktyget gör, ifall det behöver informeras hur den arbetar, och förslagsvis hur resultatet kommer se ut.
ContentTtGridInputDataBoolInfo = Variabler som ska anges som sant eller falskt innan start av funktionen. Variabeln kan även anges som obligatorisk, och måste då anges innan funktionen kan startas. Värdet för varje given variabel kommer kopieras till funktionen som en boolean.
ContentTtGridInputDataInfo = Variabler som ska anges innan start av funktionen. Variabeln kan även anges som obligatorisk, och måste då anges innan funktionen kan startas. Värdet för varje given variabel kommer kopieras till funktionen som en sträng.
ContentTtGridInputDataListInfo = Variabler som ska anges utifrån en angiven lista innan start av funktionen. Variabeln kan även anges som obligatorisk, och måste då anges innan funktionen kan startas. Värdet för varje given variabel kommer kopieras till funktionen som en sträng.
ContentTtGridInvalidateDateTimeInfo = Detta anger datum och tid då funktionen/verktyget inte längre kan användas.
ContentTtGridMenuItemInfo = Vilken text som ska visas i menyraden. Denna text får inte innehålla 'underscore' ('_') och ska tydlig med funktionens/verktygets syfte.
ContentTtGridNameInfo = Namn på funktionen/verktyget. För verktyg kommer detta vara basnamnet på fil/-erna. Namnet kan inte sättas i info-blocket i början av koden. Namnet måste ha ett godkänt verb som prefix.
ContentTtGridNoRunspaceInfo = Om funktionen anges med NoRunspace kommer koden köras i samma process som huvudfönstret. Detta kan vara bra i vissa situationer när en separat process inte kan använda nödvändiga behörigheter eller process info. Att funktionen använder samma process innebär att fönstret kommer vara låst till dess att funktionen har kört färdigt.
ContentTtGridNoteInfo = Ange information som kan vara behjälplig att visa innan funktionen startas. Texten kan anges som information eller varning.
ContentTtGridObjectClassInfo = Välj vilket objekttyp som functionen ska arbeta mot/på. Menyraden kommer placeras i motsvarande meny specifik för objekttypen. Detta gör också att funktionen kommer få tillgång till sökt objekt om typen är samma. Om detta inte väljs, kommer funktionen placeras i modulen "OtherFunctions" och menyraden placeras då i menyn "Andra funktioner".
ContentTtGridObjectOperationsInfo = Välj objekttyp som verktyget arbetar med. Menyraden kommer placeras i motsvarande meny specifik för objekttypen. Detta gör också att verktyget kommer få sökt objekt kopierat till sig när verktyget startaa. Om detta inte väljs, kommer menyraden placeras i menyn "Verktyg".
ContentTtGridOutputTypeInfo = Definiera hur data ut från funktionen är formad eller hur den ska visas. 'String' - Data kommer vara format som en sträng och kommer visas som text utan speciell formatering. 'ObjectList' - Data kommer vara en lista av objekt. Objekten kommer listas med samtliga attribut i en tabell. 'List' - Data kommer vara en lista med strängar. 'None' - Data kommer inte returneras av funktionen.
ContentTtGridRequiredAdGroupsInfo = En eller flera AD-grupper användare ska vara medlem i för att funktionen/verktyget ska vara tillgängligt. Detta har inte prioritet över AllowedUsers. Om detta lämnas tomt, kommer alla ha behörighet.
ContentTtGridSearchedItemRequestInfo = Ange vilket behov funktionen har av sökt objekt. 'None' - Inget behov och sökt objekt kommer inte kopieras till funktionen. 'Allowed' - Sökt objekt kan användas, men är inte nödvändigt. Om ett objekt har sökts och lästs in, kommer det kopieras till funktionen vid start. 'Required' - Sökt objekt behövs och menyraden kommer inte vara synlig om inget objekt har lästs in.
ContentTtGridSeparateInfo = Ange om verktyget ska skapas som ett separat verktyg. Detta innebär att GUI måste hanteras av verktyget självt och kommer därför öppnas som ett eget fönster. När verktyget ska startas, kommer en separat process skapas upp, som verktyget arbetar i. Detta innebär även att ingen information kommer vara tillgänglig i huvudfönstret. När huvudfönstret stängs, görs försök att även verktygets fönster ska stängas.
ContentTtGridStateInfo = Vilken utvecklingsfas befinner sig koden i? Dev betyder att den är under utvecklingsfas och kommer enbart kunna köras i utvecklingsmiljön. Test och Prod kommer vara tillgängliga för publicering.
ContentTtGridSubMenuInfo = Anger ifall menyraden ska placeras i en undermeny.
ContentTtGridSynopsisInfo = Synopsis, eller kort beskrivning. Denna bör vara inte längre än en mening och ska överlag beskriva funktionens/verktygets syfte.
ContentTtGridValidStartDateTimeInfo = Detta anger datum och tid då funktionen/verktyget kan börja användas.
ContentTtRbFuncNoteTypeInfo = Informationen kommer visas när funktionen startas från menyn. Om funktionen inte har någon input, men har information, kommer operationen pausas innan funktionen körs.
ContentTtRbFuncNoteTypeWarning = Anteckningen ska vara varning. Varningen kommer visas när funktionen startas från menyn. Om funktionen inte har någon input, men har en varning, kommer operationen pausas innan funktionen körs. Varningen måste bekräftas innan funktionen kan startas.
CvsFuncObjectClassList = Mapp,DirectoryInfo;Fil,FileInfo;Användare,User;Grupp,Group;Dator,Computer;Skrivare,Print queue;Annan funktion,Other;
CvsToolObjectOperationsList = Mapp,DirectoryInfo;Fil,FileInfo;Användare,User;Grupp,Group;Dator,Computer;Skrivare,Print queue;Annan funktion,Other;
ErrNewCodeTemplateAllowedUsersNotFound = En eller flera id:n hittades inte
ErrNewCodeTemplateAuthorNotFound = Hittar ingen användare med angivet namn
ErrNewCodeTemplateNoIdentifyableId = Inte ett identifierbart id
ErrNewCodeTemplateBadInvalidateDate = Giltig datumsträng för slut
ErrNewCodeTemplateBadValidDate = Giltig datumsträng för start
ErrNewCodeTemplateDefaultValNotInOptionsList = Detta värde finns inte med i listan
ErrNewCodeTemplateDescriptionEmpty = Beskrivning måste anges
ErrNewCodeTemplateDescriptionNotGiven = Beskrivning måste anges
ErrNewCodeTemplateEndBeforeNow = Slutdatum har redan varit
ErrNewCodeTemplateEndBeforeStart = Slutdatum kan inte vara före startdatum
ErrNewCodeTemplateEndParseError = Kan inte konvertera texten till giltigt datum/tid. Korrekt format är 'ÅÅÅ-MM-DD tt:mm:ss'
ErrNewCodeTemplateInputNameExists = Namnet har redan angivits för en annan indata variabel
ErrNewCodeTemplateInputNameInvalidCharacter = Namnet får endast innehålla bokstäver
ErrNewCodeTemplateMenuItemEmpty = Menyrad måste anges
ErrNewCodeTemplateMenuItemExists = Angiven text används för en annan funktion/verktyg, vilket kan bli förvirrande.
ErrNewCodeTemplateMenuItemInvalidCharacters = Texten innehåller otillåtna tecken. Texten ska bara vara bokstäver, utan underscore
ErrNewCodeTemplateMenuItemUnderscore = Texten innehåller '_' vilket kan ställa till det med kortkommandon
ErrNewCodeTemplateMissingCodeType = Ingen kodmall vald
ErrNewCodeTemplateMissingDescription = Beskrivning
ErrNewCodeTemplateMissingFuncObjectClass = Objektklass funktionen ska arbeta 
ErrNewCodeTemplateMissingFuncOutputType = Typ av utdata
ErrNewCodeTemplateMissingFuncSearchedItemRequest = Behov av sökt objekt
ErrNewCodeTemplateMissingInfo = Kan inte fortsätta då följande nödvändig information saknas
ErrNewCodeTemplateMissingInputDataBoolVarNoDesc = En eller flera indata som sant eller falskt saknar beskrivning
ErrNewCodeTemplateMissingInputDataListVarNoDesc = En eller flera indata med vallista saknar beskrivning
ErrNewCodeTemplateMissingInputDataListVarNoList = En eller flera indata med vallista saknar vallist
ErrNewCodeTemplateMissingInputDataVarNoDesc = En eller flera indata saknar beskrivning
ErrNewCodeTemplateMissingMenuItem = Menyrad
ErrNewCodeTemplateMissingName = Namn
ErrNewCodeTemplateMissingNameVerb = Verb prefix
ErrNewCodeTemplateMissingState = Utvecklingsfas
ErrNewCodeTemplateMissingSynopsis = Synopsis
ErrNewCodeTemplateRequiredAdGroupsNotFound = En eller flera namn hittades inte
ErrNewCodeTemplateStartAfterEnd = Startdatum kan inte vara efter slutdatum
ErrNewCodeTemplateStartEndSame = Start- och slutdatum kan inte vara samma
ErrNewCodeTemplateStartParseError = Kan inte konvertera texten till giltigt datum/tid. Korrekt format är 'ÅÅÅÅ-MM-DD tt:mm:ss'
ErrNewCodeTemplateStateMissing = Utvecklingsfas måste vara angiven
ErrNewCodeTemplateSubMenuInvalidCharacters = Texten för undermeny får enbart innehålla bokstäver
ErrNewCodeTemplateSynopsisEmpty = Synopsis måste anges
ErrNewcodeTemplateSynopsisUnderscore = Texten innehåller '_' vilket kan ställa till det med kortkommandon
ErrNewCommandIllegalCharacters = Namnet innehåller icke tillåtna tecken
ErrNewCommandNameExists = Det angivna namnet finns redan
ErrNewCommandNoNameInput = Ett namn måste anges
LogFailedUpdates = skript misslyckades att uppdateras
LogFailedUpdatesName = Skriptnamn
LogFailedUpdatesTestResults = Testresultat:
LogOpenDiffWindow = Kontrollerar diff
LogUpdatedIntro = Uppdaterat
StrAdmPrefix = sys
StrCheckingUpdatesCheckFiles = Kontrollerar uppdateringar
StrCheckingUpdatesGetFiles = Hämtar filer
StrDiffRowAdded = < Rad tillagd >
StrDiffRowRemoved = < Rad borttagen >
StrErrorlogsNotLoaded = Felloggar har inte lästs in
StrFailedTestCount = Antal test som felade
StrFunctionCreated = Funktion har nu skapats och placerats i modul-filen. Vill du öppna filen?
StrFunctionState = Tillhörande funktion i
StrIcInputDataBoolDescriptionTitle = Beskrivning
StrIcInputDataBoolMandatoryTitle = Obligatorisk
StrIcInputDataBoolNameTitle = Variabelnamn
StrIcInputDataDescriptionTitle = Beskrivning
StrIcInputDataListDefaultValueTitle = Standardvärde
StrIcInputDataListDescriptionTitle = Beskrivning
StrIcInputDataListMandatoryTitle = Obligatorisk
StrIcInputDataListNameTitle = Variabelnamn
StrIcInputDataListOptionslistTitle = Värdelista
StrIcInputDataMandatoryTitle = Obligatorisk
StrIcInputDataNameTitle = Variabelnamn
StrKbSummaryAcceptsSI = (Accepterar sökt objekt)
StrKbSummaryAvailableForBoTitle = Tillgängliga för BO
StrKdSummaryCommands = Funktioner / verktyg
StrKbSummaryCopied = Sammanfattning har kopierats till clipboard
StrKdSummaryDescription = Beskrivning av funktion/verktyg
StrKdSummaryMenuItem = Menyrad
StrKbSummaryNeedsSI = (Kräver sökt objekt)
StrKbSummaryPreamble = <h3>Listförklaring</h3><p>I listan visas namnet (detta är den text som visas i menyerna), samt en förklaring för vad funktionen/verktyget gör.</p><p>&nbsp;</p><h3>Förklaring olika textstilar</h3><p><em>Kursiv - Detta är ett verktyg där all GUI visas i huvudfönstret</em></p><p><strong>Fet - Detta är ett verktyg som öppnas i ett eget, separat fönster</strong></p><p><span style="text-decoration: underline;">Understruken - Detta öpnnar en länk i Chrome, eller öppnar/startar annan applikation, de flesta ger ingen output</span></p><p>&nbsp;</p><h3>Input för funktioner</h3><p>Hur input ska anges för funktioner ska informeras när funktionen initieras, antingen som ett värde, eller som flera. Detta står ovanför textrutan för input-värdet.</p><p>Ifall värdet är nödvändigt för funktionen, kommer det visas en röd stjärna. Det görs ingen kontroll av värdet, så som stavning eller att t.ex. en dator har det namnet, innan funktionen körs. Detta tas om hand av funktionen.</p><p>&nbsp;</p><h4>Kräver sökt objekt</h4><ul style="list-style-position: inside;"><li>Funktionen är markerad med grönt framför texten på menyraden</li><li><strong>Kräver</strong> att objekt har sökts och laddats in, annars kommer menyraden inte visas</li><li>Funktionen kräver enbart objektet som input och kommer starta på en gång</li></ul><h4>Accepterar sökt objekt</h4><ul style="list-style-position: inside;"><li>Funktionen är markerad med gult framför texten på menyraden</li><li>Funktionen kan arbetat med sökt objekt och tar dess namn som input</li><li>Sökt objekts namn kommer läggas in i första textrutan</li></ul><p>&nbsp;</p>
StrKbSummarySubCategoryTitlePrefix = Undermeny
StrLogInfoCopyComputerName = Datornamn
StrLogInfoCopyDate = Datum
StrLogInfoCopyError = Fel
StrLogInfoCopyErrorFilePath = Sökväg till fil
StrLogInfoCopyLogText = Loggtext
StrLogInfoCopyOperator = Handläggare
StrLogInfoCopyOutputFile = Utdata
StrLogInfoCopyOutputFilePath = Sökväg till fil
StrLogInfoCopySuccess = Lyckades
StrLogInfoCopyTitle = Logg-info för skript
StrLogSearchNoType = Ingen typ vald
StrNewFileTitle = < Ny fil >
StrNoFailedSelected = Inga filer markerade för uppdatering
StrNoScriptfile = Ingen skriptfil som innehåller information hittades
StrNotAllowedAnyway = Skript kan inte uppdateras då det bryter mot nödvändiga regler
StrNoUpdaterSpecified = <Ej angiven>
StrNoUpdates = Inga uppdaterade filer
StrRollbackDone = Fil tillbakarullad
StrRollbackInfoCopyFileLogs = Filversioner
StrRollbackInfoCopyTitle = Uppdateringshistorik för
StrRollbackInfoCopyUpdated = Datum
StrRollbackInfoCopyUpdater = Uppdaterad av
StrRollbackName = uppdaterad
StrRollbackPathNotFound = Filen hittas inte i produktion. Denna fil har troligen ersatts av annan fil, eller döpts om. Filen bör därför inte rullas tillbaka.
StrRollbackVerification = Vill du ersätta filen i produktion med denna fil?
StrRollbackVerificationDate = Filversion att rulla tillbaka:
StrRollbackVerificationPath = Fil att ersätta:
StrScriptState = Tillhörande skript i
StrSeparateToolCreated = Skriptfil har nu skapats. Vill du öppna filen?
StrUpdatedFileIsNew = Ny
StrUpdatedFileIsUpdated = Uppdaterad
StrUpdates = uppdaterade filer
StrUpdatesInProd = filer har ändrats i produktion, men inte i dev
'@
