ConvertFrom-StringData @'
CodeComputerMatch = (o1|o2)(d|l)s\\d{7}
CodeComputerMismatch = ^(o3|o4)
CodeRoleMatch = (R1|R2)
ContentbtnConnect = Anslut till dator
ContentbtnGetProfiles = Hämta profiler
ContentbtnLogoutUsers = Logga ut alla användare
ContentbtnRemoveSelected = Ta bort markerade profiler
ContentbtnReset = Reset
ContentbtnRestoreSelected = Återställ markerade profiler
ContentbtnSelectAll = Markera alla
ContentDeselectAll = Avmarkera alla
ContentgwcID = Id
ContentgwcLastUse = Senast uppdaterad
ContentgwcName = Namn
ContentgwcNameReset = Profilnamn
ContentlblComputerName = Datornamn
ContenttiProfiles = Profillista
ContenttiReset = Återställ profil/-er
StrBackupFileName = Profilbackup
StrCheckOnline = Kontrollerar anslutning mot
StrDeleteSummary = Rensat profiler på dator
StrDone = Klar
StrDoneDeleting = Finished removing profiles
StrDoneRestoring = Finished restoring profiles
StrErrAd = Annat fel vid kontroll mot AD
StrErrNoProf = Ingen profil skapad, återställer inte filer
StrErrNoProfFolder = Ingen profilmapp skapad, återställer inte profilfiler
StrErrRestore = Återställning av profil misslyckades
StrErrRestoreLog = Återställning av profil misslyckades. Errorlog har skrivits, skicka meddelande om detta i felanmälningsfliken i SDValmeny.
StrGettingProfiles = Hämtar profiler
StrInfoLogout = Skickar meddelande om utloggning
StrLoggedOutUsers = användare utloggade
StrMessageLogout = Du kommer bli utloggad av Servicedesk om 10 sekunder
StrNameNotInAd = Datornamnet kan inte hittas i AD
StrNoBackups = Inga backups funna
StrNoProfiles = Inga profiler hittades
StrNumProfileBackups = Antal profilbackuper hittade:
StrNumProfiles = Antal profiler hittade:
StrOffline = Är INTE tillgänglig
StrOnline = Är tillgänglig
StrProfiles = profiler
StrProfLoc = Sökväg för profil
StrRemoves = Tar bort Windows-profil och filer
StrRestored = återställd, från
StrRestoreSummary = återställt
StrStartBackup = Startar backup för
StrStartDeleting = Påbörjar rensning av profiler
StrStartLogout = Påbörjare utloggning av användare
StrStartRestoring = Påbörjar återställning av profiler
StrTest = Testversion, profiler kommer inte tas bort och backup kommer inte skapas
StrUsersLoginSessions = användare har inloggningssessioner
StrUsersLoginSessionsLogOut = Logga ut dessa innan du fortsätter.
StrWrongName = Datornamnet är inte giltigt och kan inte kontrolleras mot AD
StrWrongOrg = Rensning av profiler utförs enbart på datorer tillhörandes Org1, Org2. Denna tillhör annan organisation och deras separata IT-Service får hjälpa till.
StrWrongRole = Datorn har inte rätt PC-roll. En eller flera av dess roller kräver speciell hantering av IT-Service. Datorn har tilldelats följande roller:
'@
