ConvertFrom-StringData @'
ContentBtnExport = Exportera
ContentBtnReset = Återställ
ContentBtnSearch = Sök
ContentDgColReceived = Mottaget
ContentDgColReceiver = Mottagare
ContentDgColSender = Avsändare
ContentDgColSubject = Ämne
ContentTblEndTitle = Slutdatum
ContentTblFromIpTitle = Från IP
ContentTblFromIpTitleTt = Den offentliga IP-adressen för SMTP-e-postservern som skickade meddelandet
ContentTblPageSizeTitle = Antal träffar
ContentTblReceiver = Mottagare
ContentTblSender = Avsändare
ContentTblStart = Startdatum
ContentTblStatusTitle = Mottagningsstatus
ContentTblToIpTitle = Till IP
ContentTblToIpTitleTt = ToIP-parametern filtrerar resultaten efter destinationens IP-adress.\nFör utgående meddelanden är värdet på ToIP den offentliga IP-adressen i den lösta MX-posten för måldomänen.\nFör inkommande meddelanden till Exchange Online är värdet tomt.
LogExported = Exporterat data
LogSearchDates = Sökdatum
LogTraceCount = mail hittades
StrDone = Messagetrace received
StrExportDateFormat = ÅÅÅÅ-MM-DD tt:mm:ss
StrExportDefaultFileName = Messagetrace export
StrExportFileNameDates = Sökdatum
StrExportFileNameFo = Till
StrExportFileNameFrom = Från
StrExportSaved = Excel-fil har sparats
StrInvalidEmail = Ogiltig e-post adress
StrOutputFileNamePrefix = O365 Messagetrace
'@
