ConvertFrom-StringData @'
CodeGrpDescriptionMatch = \\\\(((gem)|(torg)|(app))\\$)|(dom.test.com)\\\\
CodeGrpRegExDescriptionExclude = Denna grupp skall EJ populeras med användarkonton
ContentBtnAbort = Avbryt
ContentBtnCloseStreamsList = Stäng
ContentBtnCreateQuestion = Kopiera fråga om hjälp, till Ops
ContentBtnOpenFolder = Öppna mapp
ContentBtnOpenFolderTT = Öppna mappen filen är placerad i
ContentBtnOpenSummary = Öppna fil
ContentBtnPrep = Förbered sökning
ContentBtnReset = Återställ
ContentBtnRunVirusScan = Kör virusscan
ContentBtnSearchExt = Sök filändelse
ContentBtnSearchExtTT = Sök på filändelse på Google
ContentBtnSearchFileName = Sök filnamn
ContentBtnSearchFileNameTT = Sök på filnamnet på Google
ContentBtnShowFileStreams = Visa filströmmar
ContentBtnStartSearch = Starta sökning
ContentCbSetAccountDisabled = Inaktivera kontot
ContentDgtcStreamsDataSize = Storlek
ContentDgtcStreamsName = Namn på dataströmmen
ContentLvColumnCreated = Skapad
ContentLvColumnName = Namn
ContentLvColumnOwner = Ägare
ContentLvColumnSize = Storlek
ContentLvColumnStreams = Data strömmar
ContentLvColumnUpdated = Uppdaterad
ContentRbAllToolTip = Hämtar alla filer, med ändring gjord senaste 60 dagarna. Vid sökning för alla filer, kan det ta betydligt längre tid.
ContentRbLatestToolTip = Hämtar de filer som blivit ändrade inom de senaste två veckorna
ContentRbPrevDateToolTip = Hämtar filer som ändrats efter angivet datum
ContentTblCaseNrTitle = Ange ärendenummer
ContentTblCbExpandGroups = Expandera alla filtyps-grupper
ContentTblCbGroupExtensions = Gruppera filer per filtyp
ContentTblFileCountTitle = Totalt antal filer:
ContentTblFolderCountTitle = Antal mappar som genomsöks:
ContentTblFolderListTitle = Väntar på fillista från följande mappar
ContentTblGroupInputTitle = Inställningar
ContentTblGroupSearchSettingsTitle = Sökinställningar
ContentTblGroupSummaryTitle = Sammanfattning
ContentTblIdTitle = Ange id för användare
ContentTblMDG = Filer med multipla punkter i filnamnet (potentiellt multipla filändelser)
ContentTblMDH = Filer i H-mappen med multipla punkter i filnamnet (potentiellt multipla filändelser)
ContentTblO = Mappar du inte har behörighet till, lägg ärende till Ops
ContentTblPrevDateText = Från och med angivet datum
ContentTblRbAllText = Sök alla filer
ContentTblRbLatestText = Senaste två veckorna
ContentTblStreamsListFileName = Filnamn
ContentTblStreamsListInfo = Alternativa dataströmmar för fil
ContentTblSummaryTitle = Sammanfattning skriven till:
ContentTblUserTitle = Användare:
ContentTblValuesTitle = Båda värden måste anges
ContentTiFilesHeader = Alla filer
ContentTiMDGHeader = Multipla filändelser på G:
ContentTiMDHHeader = Multipla filändelser på H:
ContentTiOHeader = Mappar du saknar behörighet till
ErrScanError = Fel uppstod
ErrScanErrorTitle = Fel vid virusscanning
LogScannedFile = Körde virusscan
LogScannedFileTitle = Filnamn
MsgRecycleBin = Filen ligger i Papperskorgen och kan inte kontrolleras.
StrEnableUser = Ska användarkontot aktiveras?
StrErrUserNotFound = ingen användare med det id:t
StrFileOwner = Användaren
StrFileSearchFinished = Finished searching for files
StrGrpDescriptionReplace = för externa användare
StrGrpDescriptionSplit = Ger Modify på
StrHomeFolder = Hemkatalog
StrLogMsgCaseNr = Ärendenummer
StrLogMsgFileSearchAborted = Avbröt filsökning
StrLogMsgFilesScannedForVirus = Dessa filer har kontrollerats med antivirus
StrLogMsgFilesWithDoubleExtG = Antal filer med eventuellt dubbla filändelser på G:
StrLogMsgFilesWithDoubleExtH = Antal filer med eventuellt dubbla filändelser på H:
StrLogMsgFolderSearch = Söker mappar
StrLogMsgId = Användar-id
StrLogMsgOpenFolder = Öppnade mapp
StrLogMsgOtherPermCount = Antal mappar där behörighet saknades:
StrLogMsgSearchExt = Sökte på filändelse
StrLogMsgSearchFileName = Sökte på filnamn
StrLogMsgSearchTime = Sökningstid
StrLogMsgTotNumFiles = Totalt antal filer
StrLogQuestionCopied = Kopierat
StrLogScriptStart = Start
StrMultiFileVirusSearch = Flertalet filer har valts, vilket kommer ta längre tid, ju fler filer som valts
StrNoExtension = <Ingen filändelse>
StrNoFilesFound = < Inga filer hittades >
StrOPGettingFiles = Startar hämtning av filer
StrOPGettingFolders = Hämtar mappar
StrOPWaitGettingFiles = Väntar hämtning av filer
StrOutput1 = Sökning av potentiella virus
StrOutput2 = Användare
StrOutput3 = Ärendenummer
StrOutput4 = Totalt antal filer:
StrOutputTimeline1 = Sökte: Filer uppdaterade senaste två veckorna
StrOutputTimeline2 = Sökte: Filer uppdaterade efter datum
StrOutputTimeline3 = Sökte: Alla tillgängliga filer
StrOutputTitleAllFiles = Alla funna filer
StrOutputTitleFolders = Genomsökta mappar
StrOutputTitleFoldersOtherPerm = Saknade behörighet för följande mappar
StrOutputTitleMultiDotG = Multipla filändelser G:
StrOutputTitleMultiDotH = Multipla filändelser H:
StrQuestion1 = har anmält eventuellt virus i ärende
StrQuestion2 = Mappar under H:\\ samt G:\\ har undersökts, men det saknas behörighet för mapparna nedan.
StrQuestion3 = Kan ni hjälpa till att titta på dessa?
StrQuestionCopied = Text har kopierats till clipboard
StrSepServer = sepser01
StrSepServerFolder1 = APP1$\\Or
StrSepServerFolder2 = APP2\`$\\Or2
StrSepServerFolder3 = APP3$\\Or3
StrUserAccountAlreadyLocked = Kontot redan inaktiverat
StrVerbVirusScan = Sök efter hot
'@
