ConvertFrom-StringData @'
ContentBtnExport = Exportera
ContentBtnGetInfo = Hämta trace info
ContentBtnReset = Återställ
ContentBtnSearch = Sök
ContentDgColReceived = Mottaget
ContentDgColReceiver = Mottagare
ContentDgColSender = Avsändare
ContentDgColStatus = Status
ContentDgColSubject = Ämne
ContentExpExtraSettings = Andra sökinställningar
ContentTblEndTitle = Slutdatum
ContentTblFromIpTitle = Från IP
ContentTblFromIpTitleTt = Den offentliga IP-adressen för SMTP-e-postservern som skickade meddelandet
ContentTblInfoActionTitle = Action
ContentTblInfoDataTitle = Data
ContentTblInfoDateTitle = Date
ContentTblInfoDetailTitle = Detail
ContentTblInfoEndDateTitle = End date
ContentTblInfoEventTitle = Event
ContentTblInfoIndexTitle = Index
ContentTblInfoOrganizationTitle = Organization
ContentTblInfoRecipientAddressTitle = Recipient address
ContentTblInfoSenderAddressTitle = Sender address
ContentTblInfoStartDateTitle = Start date
ContentTblMessageIdTitle = Message ID
ContentTblMessageTraceIdTitle = Messagetrace ID
ContentTblPageSizeTitle = Antal träffar
ContentTblReceiver = Mottagare
ContentTblSender = Avsändare
ContentTblStart = Startdatum
ContentTblStatusTitle = Mottagningsstatus
ContentTblToIpTitle = Till IP
ContentTblToIpTitleTt = ToIP-parametern filtrerar resultaten efter destinationens IP-adress.\nFör utgående meddelanden är värdet på ToIP den offentliga IP-adressen i den lösta MX-posten för måldomänen.\nFör inkommande meddelanden till Exchange Online är värdet tomt.
ContentTiInfo = Message trace details
ContentTiTrace = Message trace
ErrNoMessageTraceDetails = Ingen information hittades, prova igen
LogExported = Exporterat data
LogSearchDates = Sökdatum
LogTraceCount = mail hittades
StrDone = Messagetrace received
StrExportDateFormat = ÅÅÅÅ-MM-DD tt:mm:ss
StrExportDefaultFileName = Messagetrace export
StrExportFileNameDates = Sökdatum
StrExportFileNameFo = Till
StrExportFileNameFrom = Från
StrExportSaved = Excel-fil har sparats
StrInvalidEmail = Ogiltig e-post adress
StrOutputFileNamePrefix = O365 Messagetrace
StrStatusDelivered = Meddelandet levererades till sin destination.
StrStatusExpanded = Det fanns ingen meddelandeleverans eftersom meddelandet var adresserat till en distributionsgrupp och medlemskapet i distributionen utökades.
StrStatusFailed = Meddelandeleverans försöktes och det misslyckades eller så filtrerades meddelandet som skräppost eller skadlig kod, eller av transportregler.
StrStatusFilteredAsSpam = Meddelandet markerades som skräppost.
StrStatusGettingStatus = Meddelandet väntar på statusuppdatering.
StrStatusPending = Meddelandeleveransen pågår eller har skjutits upp och försöker igen.
StrStatusQuarantined = Meddelandet sattes i karantän.
'@
