ConvertFrom-StringData @'
ContentBtnAbortReport = Avbryt
ContentBtnSendReport = Skicka
ContentLblAuthorTitle = Författare
ContentLblDescTitle = Beskrivning
ContentTblScriptTitle = Välj en funktion eller skript i listan, skriv kommentar och klicka sedan på "Skicka"
ContentTblPropHandlerTitle = Välj en handler i listan, skriv kommentar och klicka sedan på "Skicka"
ContentTblSuggestionTitle = Förslag
ContentTBtnSuggestion = Klicka här för att formulera ett förslag
StrBackOfficeMailAddress = backoffice@test.com
StrCodeTypeFunctionTitle = Funktion
StrCodeTypePHTitle = Attribut handler
StrCodeTypeToolTitle = Verktyg
StrFeedbackSubject = Felanmälan / förslag från Fetchalon
StrFilePathTitle = Sökväg för fil
StrLogAuthorInformed = Utvecklaren har informerats
StrMessageTitle = Meddelande
StrNewSuggestion = Förslag på ny funktion/verktyg
StrNewSuggestionDescription = Kom med ett förslag på en funktion, verktyg eller attribut handler som du tycker saknas
StrNoItemSelected = Ingen funktion eller verktyg valt i trädvyn
StrNotSentToAuthor = Mail har inte skickats till författaren
StrSentToAuthor = Mail har även skickats till författare
StrSMTP = smtprelay.test.com
StrSplashAllSent = Meddelande skickat
StrSplashFinished = Tack för informationen
StrSplashToAuthor = Utvecklare informerad
StrSuggestionIntro = har kommit med följande förslag
StrSuggestionSubject = Förslag från Fetchalon
StrToAuthorInfo = Din funktion/verktyg i Fetchalon har fått en kommentar/felanmälan/förslag.
StrToAuthorInfoSentBy = Meddelandet skickades av
'@
