ConvertFrom-StringData @'
CodeSysManUri = http://sysman.test.com/
CodeWrapperHKey = HKLM:\\SOFTWARE\\Klient\\Wrapper\\
ContentBtnGetAppList = Starta hämtning
ContentBtnReset = Rensa data
ContentBtnUninstall = Avinstallera
ContentChbGetLocal = Lokala
ContentChbGetSysMan = SysMan
ContentDgAppListCoreNameCol = Namn
ContentDgLocalInstCol = Installationsdatum
ContentDgLocalNameCol = Applikationsnamn
ContentDgLocalUserCol = Installerad för ...
ContentDgSysManDescCol = Beskrivning
ContentDgSysManNameCol = Namn
ContentDgWrappersAppNameCol = Namn
ContentDgWrappersInstallDateCol = Installationsdatum
ContentDgWrappersProdVerCol = Produkt version
ContentPComputerNotFoundInAdAlertTt = Datornamn hittas inte i AD
ContentPComputerNotFoundInSysManAlertTt = Hittar ingen dator med angivet namn i SysMan
ContentTblAppListCoreTitle = Denna lista visar de applikationer som ingår i Deployment-mallen
ContentTblComputerNameTitle = Ange datornamn:
ContentTiAppListCore = Core applikationer
ContentTiAppListLocal = Lokalt
ContentTiAppListSysMan = SysMan
ContentTiAppListWrappers = Wrappers
ContenxtTblGetFromTitle = Hämta lista över applikationer
ErrComputerNotFound = Ingen dator hittades med angivet namn
ErrComputerNotReachable = Kan inte nå datorn
ErrHiveNotAccessible = Kan inte nå register hive
ErrNoWrapperFound = Hittade inte specifik wrapper, avinstallation avbruten
ErrSmComputerNotReachable = Problem hämta info från SysMan
ErrSysManUninstall = Problem vid avinstallation via SysMan
ErrWrapperUninstall = Problem uppstod vid avinstallation av wrapper:
QUninstall = Säker på att du vill avinstallera
StrAllUsers = Alla användare
StrAppSum = applikationer
StrDone = Applikation avinstallerade
StrGetApps = Hämtar applikationslista
StrInstalledForAll = Alla
StrLogAppInfoFetched = Hämtning av lokal app info klar
StrLogSmInfoFetched = Hämtning av SysMan app info klar
StrNoDate = Inget datum
StrRoleOrg = Org
StrSwitchComputer = Datorn som laddats i detta verktyg, och datorn som skickats från huvudfönstret är inte samma. Vill du byta till datorn som skickats från huvudfönstret?
StrSwitchComputer2 = Dator från huvudfönstret:
StrUninstalledWithSysMan = är nu schemalagt för avinstallation via SysMan
StrUninstalling = Avinstallerar
StrWrapperUninstallSuccess = Wrapper har avinstallerats
TblAppListLocalTitle = Denna lista visar alla applikationer som är installerade på datorn, samt om de är installerade för en enskild användare eller för alla
TblAppListSysManTitle = Denna lista visar de applikation som är angivna i SysMan
TblAppListWrappersTitle = Denna lista visar wrappers installerade på datorn
'@
