ConvertFrom-StringData @'
CodeSysManUri = http://sysman.test.com/
CodeWrapperHKey = HKLM:\\SOFTWARE\\Klient\\Wrapper\\
ContentBtnGetAppList = Hämta lista över applikationer
ContentBtnReset = Rensa data
ContentBtnUninstall = Avinstallera
ContentDgAppListCoreNameCol = Namn
ContentDgLocalInstCol = Installationsdatum
ContentDgLocalNameCol = Applikationsnamn
ContentDgLocalUserCol = Installerad för ...
ContentDgSysManDescCol = Beskrivning
ContentDgSysManNameCol = Namn
ContentDgWrappersAppNameCol = Namn
ContentDgWrappersInstallDateCol = Installationsdatum
ContentDgWrappersProdVerCol = Produkt version
ContentTblAppListCoreTitle = Denna lista visar de applikationer som ingår i Deployment-mallen
ContentTblComputerNameTitle = Ange datornamn:
ContentTiAppListCore = Core applikationer
ContentTiAppListLocal = Lokalt
ContentTiAppListSysMan = SysMan
ContentTiAppListWrappers = Wrappers
ErrComputerNotFound = Ingen dator hittades med angivet namn
ErrComputerNotReachable = Kan inte nå datorn
ErrHiveNotAccessible = Kan inte nå register hive
ErrSmComputerNotReachable = Problem hämta info från SysMan
QUninstall = Säker på att du vill avinstallera
StrAllUsers = Alla användare
StrAppSum = applikationer
StrDone = Applikationer avinstallerade
StrGetApps = Hämtar applikationslista
StrLogAppInfoFetched = Hämtning av lokal app info klar
StrLogSmInfoFetched = Hämtning av SysMan app info klar
StrNoDate = Inget datum
StrSwitchComputer = Datorn som laddats i detta verktyg, och datorn som skickats från huvudfönstret är inte samma. Vill du byta till datorn som skickats från huvudfönstret?
StrSwitchComputer2 = Dator från huvudfönstret:
StrUninstalling = Avinstallerar
TblAppListLocalTitle = Denna lista visar alla applikationer som är installerade på datorn, samt om de är installerade för en enskild användare eller för alla
TblAppListSysManTitle = Denna lista visar de applikation som är angivna i SysMan
TblAppListWrappersTitle = Denna lista visar wrappers installerade på datorn
'@
