ConvertFrom-StringData @'
GetO365AccountStatusCodeMsExchIgnoreOrg = OU=Org2
GetO365AccountStatusNotConnected = Inte ansluten till O365 services
GetO365AccountStatusParamADActiveCheck = AD Aktiv
GetO365AccountStatusParamADActiveFalse = Ej aktiv
GetO365AccountStatusParamADLockCheck = AD Olåst
GetO365AccountStatusParamADLockFalse = Kontot är låst
GetO365AccountStatusParamADMailCheck = Mailattribut angivet
GetO365AccountStatusParamADMailFalse = Mailattribut ej angivet
GetO365AccountStatusParamADmsECheck = msExchMailboxGuid är tomt
GetO365AccountStatusParamADmsEFalse = msExchMailboxGuid ej tomt
GetO365AccountStatusParamCheck = Finns i AD
GetO365AccountStatusParamOAccountCheck = O365-konto skapat
GetO365AccountStatusParamOAccountFalse = O365-konto inte skapat
GetO365AccountStatusParamOExchCheck = Synkat till Exchange
GetO365AccountStatusParamOExchFalse = Ej synkat till Exchange
GetO365AccountStatusParamOLicCheck = Har E3-licens
GetO365AccountStatusParamOLicFalse = Har ej E3-licens
GetO365AccountStatusParamOLicFalseWrongOrg = Org tilldelas inte E3
GetO365AccountStatusParamOLoginCheck = O365 inloggning aktiv
GetO365AccountStatusParamOLoginFalse = Inloggning inaktiverat
GetO365AccountStatusParamOMigCheck = Medlem i O365-MigPilots
GetO365AccountStatusParamOMigFalse = Ej medlem
GetO365AccountStatusParamTitleType = Kontroll
GetO365AccountStatusParamTitleValue = Status
GetO365AccountStatusValOk = OK
GetSharedAccountsByDepIdAdSearchBasePrefix = ou=Custom,ou=Users,ou=
GetSharedAccountsByDepIdAdSearchBaseSuffix = ,ou=Dep,dc=Domain,dc=DC
GetSharedAccountsByDepIdDepAdProp = ADPropName
GetSharedAccountsByDepIdNoAccounts = Inga konton hittades
GetSharedAccountsByDepIdObjClass = ADObjClass
GetSharedAccountsByDepIdOrgRegex = (Org0|Org1|Org2)
GetSharedAccountsByDepIdPropTitleActive = Aktivt konto
GetSharedAccountsByDepIdPropTitleComputer = På dator
GetSharedAccountsByDepIdPropTitleDepId = Kostnadsställe
GetSharedAccountsByDepIdPropTitleName = Delat konto
GetSharedAccountsByDepIdPropTitlePwdExpDate = Lösenordet går ut
GetSharedAccountsByDepIdPropTitlePwdExpDateLong = dagar, anmäl detta till tredje linan
GetSharedAccountsByDepIdPropTitlePwdExpDateNo = Går inte ut
GetSharedAccountsByDepIdPropTitlePwdLocked = Låst pga fel lösen
GetSharedAccountsByDepIdPropTitleType = Kontotyp
GetSharedAccountsByDepIdPropValNo = Nej
GetSharedAccountsByDepIdPropValYes = Ja
RemoveProfileVKNotValidOrg = Organisationen använder inte vKlient
RemoveProfileVKProfileRemoved = Klient-profilen har nu tagits bort
RemoveProfileVKQuestion = Vilken organisation arbetar användare i?
RemoveProfileVKQuestionReturn = Mapp öppnad i Utforskaren
RemoveProfileVKQuestionTitle = Ange organisation
RemoveProfileVKTCSelectCustomer = Kunde inte uttyda organisation, för vilken organisation ska profilen rensas?
RemoveProfileVKTCSelectCustomerTitle = Välj organisation
StrCompareUserGroupsNoValidUsers = Inte tillräckligt många användare att jämföra
StrGetFolderMembershipPropCodeNotMatch = .*_App_Office(key|_Mallar).*
StrGetFolderMembershipPropCodeReplace1 = \\\\\\\\dfs\\\\gem\\$
StrGetFolderMembershipPropCodeReplace2 = \\\\\\\\dfs\\\\org2\\$
StrGetFolderMembershipPropCodeSplit1 = på
StrGetFolderMembershipPropTitleFolder = Mapp
StrGetFolderMembershipPropTitleGroup = AD-grupp
StrGetFolderMembershipPropTitlePermission = Behörighetstyp
StrGetFolderMembershipPropValRead = Läsa
StrGetFolderMembershipPropValWrite = Skriva
SysManServerUrl = http://sysman.test.com/
'@
